#!/bin/sh
set -e

case "$1" in
  abort-upgrade|abort-remove|abort-deconfigure|configure)
    ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

if ! getent passwd drone >/dev/null; then
    adduser --quiet --system --group --no-create-home \
        --home /var/lib/drone drone
fi

# Add to docker group if available
if getent group docker >/dev/null; then
    gpasswd --add drone docker >/dev/null
fi

if ! dpkg-statoverride --list --quiet "/var/lib/drone" >/dev/null; then
    dpkg-statoverride --force --quiet --update \
        --add drone drone 0755 "/var/lib/drone"
fi

echo "Starting drone ..."
if [ -f /etc/init/drone.conf ]; then
    if pidof /usr/local/bin/droned >/dev/null; then
        service drone stop || exit $?
    fi
    service drone start && echo "Drone started."
fi

#DEBHELPER#

exit 0
