workspace:
  base: /drone
  path: src/github.com/drone/drone

script:
  test:
    image: drone/golang:1.5
    environment:
      - GO15VENDOREXPERIMENT=1
      - GOPATH=/drone
    commands:
      - make deps gen
      - make test test_postgres test_mysql
  dist:
    image: drone/golang:1.5
    environment:
      - GO15VENDOREXPERIMENT=1
      - GOPATH=/drone
    commands:
      - make build
    when:
      event: push

  docker:
    repo: drone/drone
    tag: [ "0.5.0" ]
    when:
      branch: master
      event: push

services:
  postgres:
    image: postgres:9.4.5
    environment:
      - POSTGRES_USER=postgres
  mysql:
    image: mysql:5.6.27
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
