image: go1.3
git:
  path: github.com/drone/drone
env:
  - GOROOT=/usr/local/go
  - PATH=$PATH:$GOROOT/bin:$GOPATH/bin
script:
  - git clone git://github.com/gin-gonic/gin.git $GOPATH/src/github.com/gin-gonic/gin
  - go get -u github.com/jteeuwen/go-bindata/...
  - make bindata deps
  - make build
  - make test
  - make dist

notify:
  email:
    recipients:
      - brad@drone.io

publish:
  s3:
    acl: public-read
    region: us-east-1
    bucket: downloads.drone.io
    access_key: $$AWS_KEY
    secret_key: $$AWS_SECRET
    source: dist/drone.deb
    target: $DRONE_BRANCH/
    when:
      owner: drone

# new .drone.yml syntax

clone:
  path: github.com/drone/drone

build:
  image: golang:1.4.2
  commands:
    - export GOPATH=/drone
    - export PATH=$PATH:$GOPATH/bin
    - go get -u github.com/jteeuwen/go-bindata/...
    - make bindata deps
    - make build
    - make test