image: bradrydzewski/go:1.5

git:
  path: github.com/drone/drone

env:
  - GOROOT=/usr/local/go
  - PATH=$PATH:$GOROOT/bin:$GOPATH/bin

script:
  - sudo apt-get -y -qq update
  - sudo apt-get -y -qq install libsqlite3-dev
  - make deps
  - make
  - make test
  - make deb

notify:
  email:
    recipients:
      - brad@drone.io

publish:
  s3:
    acl: public-read
    region: us-east-1
    bucket: downloads.drone.io
    access_key: $$AWS_KEY
    secret_key: $$AWS_SECRET
    source: contrib/debian/drone.deb
    target: $DRONE_BRANCH/
    when:
      owner: drone



---

clone:
  path: github.com/drone/drone

build:
  image: golang:1.5
  commands:
    - apt-get -y -qq update
    - apt-get -y -qq install libsqlite3-dev
    - make deps
    - make gen
    - make test
    - make build
    - make build_static
    - make deb
