image: go1.2
env:
  - GOROOT=/usr/local/go
script:
  - sudo apt-get -y install libsqlite3-dev sqlite3 1> /dev/null 2> /dev/null
  - make deps
  - make
  - make test
  - make dpkg
notify:
  email:
    recipients:
      - brad@drone.io

#publish:
#  s3:
#    acl: public-read
#    region: us-east-1
#    bucket: downloads.drone.io
#    access_key: $AWS_KEY
#    secret_key: $AWS_SECRET
#    source: deb/drone.deb
#    target: exp/
