image: go1.3
git:
  path: github.com/drone/drone
env:
  - GOROOT=/usr/local/go
  - PATH=$PATH:$GOROOT/bin:$GOPATH/bin
script:
  - git clone git://github.com/gin-gonic/gin.git $GOPATH/src/github.com/gin-gonic/gin
  - go get -u github.com/jteeuwen/go-bindata/...
  - make bindata deps
  - make build
  - make test

notify:
  email:
    recipients:
      - brad@drone.io

# new .drone.yml syntax

clone:
  path: github.com/drone/drone

build:
  image: golang:1.4.2
  commands:
    - export GOPATH=/drone
    - export PATH=$PATH:$GOPATH/bin
    - go get -u github.com/jteeuwen/go-bindata/...
    - make bindata deps
    - make build
    - make test