image: npateriyainsecure/drone-go:1.5

git:
  path: github.com/drone/drone

env:
  - GOROOT=/usr/local/go
  - PATH=$PATH:$GOROOT/bin:$GOPATH/bin

script:
  - set -x
  - go get golang.org/x/tools/cmd/cover
  - go get golang.org/x/tools/cmd/vet
  - go get -u github.com/jteeuwen/go-bindata/...

  - go run make.go deps
  - go run make.go bindata
  - go run make.go vet
  - go run make.go fmt
  - go run make.go build
  - go run make.go test

  - make dist

notify:
  email:
    recipients:
      - brad@drone.io

publish:
  s3:
    acl: public-read
    region: us-east-1
    bucket: downloads.drone.io
    access_key: $$AWS_KEY
    secret_key: $$AWS_SECRET
    source: dist/drone.deb
    target: $DRONE_BRANCH/
    when:
      owner: drone
  docker:
    docker_file: ./Dockerfile.alpine
    docker_version: 1.5.0
    docker_host: $$DOCKER_HOST
    registry_login: true
    username: $$DOCKERHUB_USER
    password: $$DOCKERHUB_PASS
    email: npateriya@yahoo.com
    image_name: npateriyainsecure/ciscodrone04
    push_latest: true
    tags:
      - $DRONE_COMMIT
      - latest
    when:
      owner: CiscoCloud



clone:
  path: github.com/drone/drone

build:
  image: golang:1.5.0
  commands:
    - export GOPATH=/drone
    - export PATH=$PATH:$GOPATH/bin
    - go get -u github.com/jteeuwen/go-bindata/...

    - go run make.go deps
    - go run make.go bindata
    - go run make.go vet
    - go run make.go fmt
    - go run make.go build
    - go run make.go test

    - make dist

compose:
  database:
    image: mysql:5.5
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=test
