## Golden config for golangci-lint v1.49.0

# This file contains only configs which differ from defaults.
# All possible options can be found here https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml
linters-settings:

  errcheck:
    # Report about not checking of errors in type assertions: `a := b.(MyStruct)`.
    # Such cases aren't reported by default.
    # Default: false
    check-type-assertions: true

  gocritic:
    # Settings passed to gocritic.
    # The settings key is the name of a supported gocritic checker.
    # The list of supported checkers can be find in https://go-critic.github.io/overview.
    settings:
      captLocal:
        # Whether to restrict checker to params only.
        # Default: true
        paramsOnly: false
      underef:
        # Whether to skip (*x).method() calls where x is a pointer receiver.
        # Default: true
        skipRecvDeref: false

  gomodguard:
    blocked:
      # List of blocked modules.
      # Default: []
      modules:
        - github.com/golang/protobuf:
            recommendations:
              - google.golang.org/protobuf
            reason: "see https://developers.google.com/protocol-buffers/docs/reference/go/faq#modules"
        - github.com/satori/go.uuid:
            recommendations:
              - github.com/google/uuid
            reason: "satori's package is not maintained"
        - github.com/gofrs/uuid:
            recommendations:
              - github.com/google/uuid
            reason: "see recommendation from dev-infra team: https://confluence.gtforge.com/x/gQI6Aw"

  govet:
    # Enable all analyzers.
    # Default: false
    enable-all: true
    # Disable analyzers by name.
    # Run `go tool vet help` to see all analyzers.
    # Default: []
    disable:
      - fieldalignment # too strict
    # Settings per analyzer.
    settings:
      shadow:
        # Whether to be strict about shadowing; can be noisy.
        # Default: false
        strict: true

  nakedret:
    # Make an issue if func has more lines of code than this setting, and it has naked returns.
    # Default: 30
    max-func-lines: 30

  rowserrcheck:
    # database/sql is always checked
    # Default: []
    packages:
      - github.com/jmoiron/sqlx

  tenv:
    # The option `all` will run against whole test files (`_test.go`) regardless of method/function signatures.
    # Otherwise, only methods that take `*testing.T`, `*testing.B`, and `testing.TB` as arguments are checked.
    # Default: false
    all: true

  goheader:
    # The template use for checking.
    # Default: ""
    template: |-
      Copyright 2023 Harness, Inc.

      Licensed under the Apache License, Version 2.0 (the "License");
      you may not use this file except in compliance with the License.
      You may obtain a copy of the License at
      
          http://www.apache.org/licenses/LICENSE-2.0

      Unless required by applicable law or agreed to in writing, software
      distributed under the License is distributed on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      See the License for the specific language governing permissions and
      limitations under the License.
    # As alternative of directive 'template', you may put the path to file with the template source.
    # Useful if you need to load the template from a specific file.
    # Default: ""
    # template-path: /path/to/my/template.tmpl
  gci:
    # DEPRECATED: use `sections` and `prefix(github.com/org/project)` instead.
    # local-prefixes: github.com/harness/gitness
    # Section configuration to compare against.
    # Section names are case-insensitive and may contain parameters in ().
    # The default order of sections is `standard > default > custom > blank > dot`,
    # If `custom-order` is `true`, it follows the order of `sections` option.
    # Default: ["standard", "default"]
    sections:
      - standard # Standard section: captures all standard packages.
      - prefix(github.com/harness/gitness) # Custom section: groups all imports with the specified Prefix.
      - default # Default section: contains all imports that could not be matched to another section type.
      - blank # Blank section: contains all blank imports. This section is not present unless explicitly enabled.
      - dot # Dot section: contains all dot imports. This section is not present unless explicitly enabled.
    # Skip generated files.
    # Default: true
    skip-generated: false
    # Enable custom order of sections.
    # If `true`, make the section order the same as the order of `sections`.
    # Default: false
    custom-order: true

  tagliatelle:
    # Check the struck tag name case.
    case:
      rules:
        # Any struct tag type can be used.
        # Support string case: `camel`, `pascal`, `kebab`, `snake`, `goCamel`, `goPascal`, `goKebab`, `goSnake`, `upper`, `lower`
        json: snake
        db: snake
        yaml: snake
        xml: snake
        bson: snake
        avro: snake
        mapstructure: snake


linters:
  disable-all: true
  enable:
    ## enabled by default
    - errcheck # checking for unchecked errors, these unchecked errors can be critical bugs in some cases
    - gosimple # specializes in simplifying a code
    - govet # reports suspicious constructs, such as Printf calls whose arguments do not align with the format string
    - ineffassign # detects when assignments to existing variables are not used
    - staticcheck # is a go vet on steroids, applying a ton of static analysis checks
    - typecheck # like the front-end of a Go compiler, parses and type-checks Go code
    - unused # checks for unused constants, variables, functions and types

    ## disabled by default
    - asasalint # checks for pass []any as any in variadic func(...any)
    - asciicheck # checks that your code does not contain non-ASCII identifiers
    - bidichk # checks for dangerous unicode character sequences
    - bodyclose # checks whether HTTP response body is closed successfully
    - contextcheck # checks the function whether use a non-inherited context
    # - dupl # tool for code clone detection
    - durationcheck # checks for two durations multiplied together
    - errname # checks that sentinel errors are prefixed with the Err and error types are suffixed with the Error
    - errorlint # finds code that will cause problems with the error wrapping scheme introduced in Go 1.13
    - exhaustive # checks exhaustiveness of enum switch statements
    - copyloopvar # linter detects places where loop variables are copied
    - forbidigo # forbids identifiers
    - goconst # finds repeated strings that could be replaced by a constant
    - gocritic # provides diagnostics that check for bugs, performance and style issues
    - godot # checks if comments end in a period
    - goimports # in addition to fixing imports, goimports also formats your code in the same style as gofmt
    - gomoddirectives # manages the use of 'replace', 'retract', and 'excludes' directives in go.mod
    - gomodguard # allow and block lists linter for direct Go module dependencies. This is different from depguard where there are different block types for example version constraints and module recommendations
    - goprintffuncname # checks that printf-like functions are named with f at the end
    - gosec # inspects source code for security problems
    - lll # reports long lines
    - makezero # finds slice declarations with non-zero initial length
    - nakedret # finds naked returns in functions greater than a specified function length
    - nestif # reports deeply nested if statements
    - nilerr # finds the code that returns nil even if it checks that the error is not nil
    - nilnil # checks that there is no simultaneous return of nil error and an invalid value
    - noctx # finds sending http request without context.Context
    # - nonamedreturns # reports all named returns
    - nosprintfhostport # checks for misuse of Sprintf to construct a host with port in a URL
    - predeclared # finds code that shadows one of Go's predeclared identifiers
    - promlinter # checks Prometheus metrics naming via promlint
    - reassign # checks that package variables are not reassigned
    - revive # fast, configurable, extensible, flexible, and beautiful linter for Go, drop-in replacement of golint
    - rowserrcheck # checks whether Err of rows is checked successfully
    - sqlclosecheck # checks that sql.Rows and sql.Stmt are closed
    - stylecheck # is a replacement for golint
    - tagliatelle # checks the struct tags
    - tenv # detects using os.Setenv instead of t.Setenv since Go1.17
    - tparallel # detects inappropriate usage of t.Parallel() method in your Go test codes
    - unconvert # removes unnecessary type conversions
    - unparam # reports unused function parameters
    - usestdlibvars # detects the possibility to use variables/constants from the Go standard library
    - wastedassign # finds wasted assignment statements
    - whitespace # detects leading and trailing whitespace

    ## you may want to enable
    #- decorder # checks declaration order and count of types, constants, variables and functions
    #- exhaustruct # checks if all structure fields are initialized
    - gci # controls golang package import order and makes it always deterministic
    #- godox # detects FIXME, TODO and other comment keywords
    - goheader # checks is file header matches to pattern
    - misspell # [useless] finds commonly misspelled English words in comments

run:
  skip-dirs:
    - registry/app/api/controller/mocks

issues:
  # Maximum count of issues with the same text.
  # Set to 0 to disable.
  # Default: 3
  max-same-issues: 10

  exclude-rules:
    - text: 'shadow: declaration of "(err|ctx|ok)" shadows declaration at'
      linters: [ govet ]
    - source: "^//\\s*go:generate\\s"
      linters: [ lll ]
    - text: 'local replacement are not allowed: github.com/harness/gitness'
      linters: [ gomoddirectives ]
    - text: 'replacement are not allowed: github.com/docker/docker'
      linters: [ gomoddirectives ]
    - source: "(noinspection|TODO)"
      linters: [ godot ]
    - source: "//noinspection"
      linters: [ gocritic ]
    - source: "^\\s+if _, ok := err\\.\\([^.]+\\.InternalError\\); ok {"
      linters: [ errorlint ]
    - path: "^cli/"
      linters: [forbidigo]
    #Registry Specific
    - path: "^registry/app/manifest/.*"
      linters: [ tagliatelle, staticcheck, revive ]
    - path: "^registry/app/dist_temp/.*"
      linters: [ errorlint ]
    - path: "^registry/app/driver/filesystem/.*"
      linters: [ gocritic ]
    - path: "^registry/app/driver/s3-aws/.*"
      linters: [ gocognit, gosec, nestif]
    - path: "^registry/app/remote/clients/registry/interceptor/interceptor.go"
      linters: [ goheader ]
    - path: "^registry/app/common/http/modifier/modifier.go"
      linters: [ goheader ]
    - path: "^registry/app/driver/fileinfo.go"
      linters: [ goheader ]
    - path: "^registry/app/driver/storagedriver.go"
      linters: [ goheader ]
    - path: "^registry/app/driver/walk.go"
      linters: [ goheader ]
    - path: "^registry/app/dist_temp/challenge/addr.go"
      linters: [ goheader ]
    - path: "^registry/app/dist_temp/challenge/authchallenge.go"
      linters: [ goheader ]
    - path: "^registry/app/dist_temp/challenge/authchallenge_test.go"
      linters: [ goheader ]
    - path: "^registry/app/dist_temp/requestutil/util.go"
      linters: [ goheader ]
    - path: "^registry/app/dist_temp/requestutil/util_test.go"
      linters: [ goheader ]
    - path: "^registry/app/pkg/commons/zipreader/*"
      linters: [ goheader ]
    - path: "^registry/app/manifest/descriptor.go"
      linters: [ goheader ]
    - path: "^registry/app/manifest/doc.go"
      linters: [ goheader ]
    - path: "^registry/app/manifest/errors.go"
      linters: [ goheader ]
    - path: "^registry/app/manifest/manifests.go"
      linters: [ goheader ]
    - path: "^registry/app/manifest/versioned.go"
      linters: [ goheader ]
    - path: "^registry/app/common/lib/authorizer.go"
      linters: [ goheader ]
    - path: "^registry/app/common/lib/link.go"
      linters: [ goheader ]
    - path: "^registry/app/common/http/tls.go"
      linters: [ goheader ]
    - path: "^registry/app/common/http/transport.go"
      linters: [ goheader ]
    - path: "^registry/app/common/http/transport_test.go"
      linters: [ goheader ]
    - path: "^registry/app/manifest/schema2/manifest.go"
      linters: [ goheader ]
    - path: "^registry/app/manifest/schema2/manifest_test.go"
      linters: [ goheader ]
    - path: "^registry/app/manifest/ocischema/index.go"
      linters: [ goheader ]
    - path: "^registry/app/manifest/ocischema/manifest.go"
      linters: [ goheader ]
    - path: "^registry/app/remote/clients/registry/auth/null/authorizer.go"
      linters: [ goheader ]
    - path: "^registry/app/remote/clients/registry/auth/basic/authorizer.go"
      linters: [ goheader ]
    - path: "^registry/app/remote/clients/registry/auth/basic/authorizer_test.go"
      linters: [ goheader ]
    - path: "^registry/app/common/lib/errors/const.go"
      linters: [ goheader ]
    - path: "^registry/app/common/lib/errors/errors.go"
      linters: [ goheader ]
    - path: "^registry/app/common/lib/errors/stack.go"
      linters: [ goheader ]
    - path: "^registry/app/common/lib/errors/stack_test.go"
      linters: [ goheader ]
    - path: "^registry/app/remote/clients/registry/auth/bearer/authorizer.go"
      linters: [ goheader ]
    - path: "^registry/app/remote/clients/registry/auth/bearer/cache.go"
      linters: [ goheader ]
    - path: "^registry/app/remote/clients/registry/auth/bearer/scope.go"
      linters: [ goheader ]
    - path: "^registry/app/manifest/manifestlist/manifestlist.go"
      linters: [ goheader ]
    - path: "^registry/app/manifest/manifestlist/manifestlist_test.go"
      linters: [ goheader ]
    - path: "^registry/app/driver/factory/factory.go"
      linters: [ goheader ]
    - path: "^registry/app/dist_temp/dcontext/context.go"
      linters: [ goheader ]
    - path: "^registry/app/dist_temp/dcontext/doc.go"
      linters: [ goheader ]
    - path: "^registry/app/dist_temp/dcontext/http.go"
      linters: [ goheader ]
    - path: "^registry/app/dist_temp/dcontext/logger.go"
      linters: [ goheader ]
    - path: "^registry/app/dist_temp/dcontext/trace.go"
      linters: [ goheader ]
    - path: "^registry/app/dist_temp/dcontext/util.go"
      linters: [ goheader ]
    - path: "^registry/app/dist_temp/dcontext/version.go"
      linters: [ goheader ]
    - path: "^registry/app/dist_temp/dcontext/http_test.go"
      linters: [ goheader ]
    - path: "^registry/app/dist_temp/dcontext/trace_test.go"
      linters: [ goheader ]
    - path: "^registry/app/dist_temp/dcontext/version_test.go"
      linters: [ goheader ]
    - path: "^registry/app/driver/base/base.go"
      linters: [ goheader ]
    - path: "^registry/app/driver/base/regulator.go"
      linters: [ goheader ]
    - path: "^registry/app/driver/base/regulator_test.go"
      linters: [ goheader ]
    - path: "^registry/app/storage/blobs.go"
      linters: [ goheader ]
    - path: "^registry/app/storage/blobwriter.go"
      linters: [ goheader ]
    - path: "^registry/app/storage/blobwriter_resumable.go"
      linters: [ goheader ]
    - path: "^registry/app/storage/errors.go"
      linters: [ goheader ]
    - path: "^registry/app/storage/filereader.go"
      linters: [ goheader ]
    - path: "^registry/app/storage/gcstoragelient.go"
      linters: [ goheader ]
    - path: "^registry/app/storage/io.go"
      linters: [ goheader ]
    - path: "^registry/app/storage/middleware.go"
      linters: [ goheader ]
    - path: "^registry/app/storage/ociblobstore.go"
      linters: [ goheader ]
    - path: "^registry/app/storage/paths.go"
      linters: [ goheader ]
    - path: "^registry/app/storage/storageservice.go"
      linters: [ goheader ]
    - path: "^registry/app/remote/clients/registry/client.go"
      linters: [ goheader ]
    - path: "^registry/app/remote/adapter/adapter.go"
      linters: [ goheader ]
    - path: "^registry/app/remote/clients/registry/auth/authorizer.go"
      linters: [ goheader ]
    - path: "^registry/app/driver/s3-aws/s3.go"
      linters: [ goheader ]
    - path: "^registry/app/driver/s3-aws/s3_v2_signer.go"
      linters: [ goheader ]
    - path: "^registry/app/driver/filesystem/driver.go"
      linters: [ goheader ]
    - path: "^registry/app/pkg/docker/app.go"
      linters: [ goheader ]
    - path: "^registry/app/pkg/docker/catalog.go"
      linters: [ goheader ]
    - path: "^registry/app/pkg/docker/compat.go"
      linters: [ goheader ]
    - path: "^registry/app/pkg/docker/context.go"
      linters: [ goheader ]
    - path: "^registry/app/pkg/docker/controller.go"
      linters: [ goheader ]
    - path: "^registry/app/pkg/docker/local.go"
      linters: [ goheader ]
    - path: "^registry/app/pkg/docker/manifest_service.go"
      linters: [ goheader ]
    - path: "^registry/app/pkg/docker/remote.go"
      linters: [ goheader ]
    - path: "^registry/app/remote/adapter/dockerhub/adapter.go"
      linters: [ goheader ]
    - path: "^registry/app/remote/adapter/awsecr/adapter.go"
      linters: [ goheader ]
    - path: "^registry/app/remote/adapter/maven/adapter.go"
      linters: [ goheader ]
    - path: "^registry/app/remote/adapter/awsecr/auth.go"
      linters: [ goheader ]
    - path: "^registry/app/remote/adapter/dockerhub/client.go"
      linters: [ goheader ]
    - path: "^registry/app/remote/adapter/dockerhub/consts.go"
      linters: [ goheader ]
    - path: "^registry/app/driver/testsuites/testsuites.go"
      linters: [ goheader ]
    - path: "^registry/app/dist_temp/errcode/errors.go"
      linters: [ goheader ]
    - path: "^registry/app/dist_temp/errcode/handler.go"
      linters: [ goheader ]
    - path: "^registry/app/dist_temp/errcode/register.go"
      linters: [ goheader ]
    - path: "^registry/app/remote/controller/proxy/controller.go"
      linters: [ goheader ]
    - path: "^registry/app/remote/controller/proxy/inflight.go"
      linters: [ goheader ]
    - path: "^registry/app/remote/controller/proxy/local.go"
      linters: [ goheader ]
    - path: "^registry/app/remote/controller/proxy/remote.go"
      linters: [ goheader ]
    - path: "^registry/app/remote/controller/proxy/inflight_test.go"
      linters: [ goheader ]
    - path: "^registry/app/remote/adapter/native/adapter.go"
      linters: [ goheader ]
    - path: "^registry/app/storage/blobStore.go"
      linters: [ gosec ]
    - path: "^registry/app/metadata/nuget/metadata.go"
      linters: [ tagliatelle, lll ]