# build environment used in .drone.yml
#
#     docker build --rm=true -t drone/golang:1.5 -f Dockerfile.env .

FROM golang:1.5
ADD contrib/*.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/setup-sassc.sh && \
    chmod +x /usr/local/bin/setup-sqlite.sh && \
    /usr/local/bin/setup-sassc.sh && \
    /usr/local/bin/setup-sqlite.sh
