FROM alpine:3.6

RUN apk add -U --no-cache ca-certificates && rm -rf /var/cache/apk/*

ENV GODEBUG=netdns=go
ADD release/drone-agent /bin/

EXPOSE 3000
HEALTHCHECK CMD ["/bin/drone-agent", "ping"]

ENTRYPOINT ["/bin/drone-agent"]

