# build environment used in .drone.yml
#
#     docker build --rm=true -t drone/golang -f Dockerfile.env .

FROM gliderlabs/alpine:3.1
RUN apk update && apk add ca-certificates curl git mercurial bzr perl openssh go && rm -rf /var/cache/apk/*

ENV GOROOT /usr/lib/go
ENV GOPATH /drone
ENV GOBIN /drone/bin
ENV PATH $PATH:$GOROOT/bin:$GOPATH/bin
