package tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit"
)

/*DeleteTaskNoContent Task deleted

swagger:response deleteTaskNoContent
*/
type DeleteTaskNoContent struct {
}

// NewDeleteTaskNoContent creates DeleteTaskNoContent with default headers values
func NewDeleteTaskNoContent() *DeleteTaskNoContent {
	return &DeleteTaskNoContent{}
}

// WriteResponse to the client
func (o *DeleteTaskNoContent) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(204)
}

/*DeleteTaskDefault delete task default

swagger:response deleteTaskDefault
*/
type DeleteTaskDefault struct {
	_statusCode int
}

// NewDeleteTaskDefault creates DeleteTaskDefault with default headers values
func NewDeleteTaskDefault(code int) *DeleteTaskDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteTaskDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete task default response
func (o *DeleteTaskDefault) WithStatusCode(code int) *DeleteTaskDefault {
	o._statusCode = code
	return o
}

// WriteResponse to the client
func (o *DeleteTaskDefault) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(o._statusCode)
}
