/**
 * This file is auto-generated. Please do not modify this file manually.
 * Use the command `yarn strings` to regenerate this file.
 */
export interface StringsMap {
  activeBranches: string
  addComment: string
  addGitIgnore: string
  addLicense: string
  addReadMe: string
  all: string
  allBranches: string
  allEvents: string
  botAlerts: string
  branch: string
  branchCreated: string
  branchDeleted: string
  branchDivergenceAhead: string
  branchDivergenceAheadBehind: string
  branchDivergenceBehind: string
  branchName: string
  branchNotFound: string
  branchProtectionRules: string
  branchSource: string
  branchSourceDesc: string
  branchTagCreation: string
  branchTagDeletion: string
  branchUpToDate: string
  branches: string
  browse: string
  cancel: string
  checkRuns: string
  checkSuites: string
  clone: string
  cloneHTTPS: string
  closed: string
  comment: string
  commit: string
  commitChanges: string
  commitDirectlyTo: string
  commitMessage: string
  commitToNewBranch: string
  commits: string
  commitsOn: string
  compare: string
  comparingChanges: string
  confirm: string
  confirmation: string
  content: string
  conversation: string
  copy: string
  copyCommitSHA: string
  create: string
  createABranch: string
  createBranch: string
  createBranchFromBranch: string
  createBranchFromTag: string
  createFile: string
  createPullRequest: string
  createRepo: string
  'createRepoModal.branch': string
  'createRepoModal.branchLabel': string
  'createRepoModal.privateLabel': string
  'createRepoModal.publicLabel': string
  createWebhook: string
  defaultBranch: string
  delete: string
  deleteBranch: string
  deleteBranchConfirm: string
  deleteFile: string
  deleteNotAllowed: string
  deployKeys: string
  description: string
  diff: string
  edit: string
  editFile: string
  editNotAllowed: string
  email: string
  enableSSLVerification: string
  enterDescription: string
  enterNewBranchName: string
  enterRepoName: string
  existingAccount: string
  failedToCreateBranch: string
  failedToCreateRepo: string
  failedToDeleteBranch: string
  fileDeleted: string
  files: string
  filesChanged: string
  findATag: string
  findBranch: string
  findOrCreateBranch: string
  general: string
  history: string
  in: string
  inactiveBranches: string
  individualEvents: string
  leaveAComment: string
  loading: string
  merged: string
  name: string
  nameYourBranch: string
  nameYourFile: string
  newFile: string
  newFileNotAllowed: string
  newFolder: string
  newPullRequest: string
  newRepo: string
  next: string
  noAccount: string
  noWebHooks: string
  none: string
  ok: string
  onDate: string
  open: string
  optional: string
  optionalExtendedDescription: string
  pageNotFound: string
  password: string
  payloadUrl: string
  payloadUrlLabel: string
  'pr.ableToMerge': string
  'pr.buttonText': string
  'pr.cantMerge': string
  'pr.descriptionPlaceHolder': string
  'pr.diffStatsLabel': string
  'pr.diffStatus': string
  'pr.diffView': string
  'pr.failedToCreate': string
  'pr.fileDeleted': string
  'pr.fileUnchanged': string
  'pr.metaLine': string
  'pr.modalTitle': string
  'pr.openBy': string
  'pr.reviewChanges': string
  'pr.showDiff': string
  'pr.showLink': string
  'pr.split': string
  'pr.state': string
  'pr.titlePlaceHolder': string
  'pr.unified': string
  prefixBase: string
  prefixCompare: string
  prev: string
  private: string
  public: string
  pullMustBeMadeFromBranches: string
  pullRequestEmpty: string
  pullRequests: string
  pushEvent: string
  rejected: string
  renameFile: string
  replyHere: string
  'repos.activities': string
  'repos.data': string
  'repos.enterBranchName': string
  'repos.lastChange': string
  'repos.name': string
  'repos.noDataMessage': string
  'repos.updated': string
  repositories: string
  samplePayloadUrl: string
  scanAlerts: string
  scrollToTop: string
  search: string
  searchBranches: string
  secret: string
  selectBranchPlaceHolder: string
  selectToViewMore: string
  settings: string
  signIn: string
  signUp: string
  sslVerificationLabel: string
  status: string
  switchBranchesTags: string
  tagNotFound: string
  tags: string
  title: string
  updateFile: string
  updated: string
  'validation.gitBranchNameInvalid': string
  'validation.repoNamePatternIsNotValid': string
  viewAllBranches: string
  viewAllTags: string
  viewCommitDetails: string
  viewed: string
  webhook: string
  webhookEventsLabel: string
  webhookListingContent: string
  webhooks: string
  yourBranches: string
  yours: string
}
