/**
 * This file is auto-generated. Please do not modify this file manually.
 * Use the command `yarn strings` to regenerate this file.
 */
export interface StringsMap {
  accessControl: string
  accountEmail: string
  accountSetting: string
  active: string
  activeBranches: string
  add: string
  addComment: string
  addGitIgnore: string
  addLicense: string
  addMember: string
  addNewFile: string
  addReadMe: string
  addUser: string
  admin: string
  all: string
  allBranches: string
  allComments: string
  allCommits: string
  alreadyHaveAccount: string
  and: string
  applyChanges: string
  approve: string
  ascending: string
  assignPeople: string
  basedOn: string
  blame: string
  blameCommitLine: string
  botAlerts: string
  branch: string
  branchCreated: string
  branchDeleted: string
  branchDivergenceAhead: string
  branchDivergenceAheadBehind: string
  branchDivergenceBehind: string
  branchDoesNotHaveFile: string
  branchName: string
  branchNotFound: string
  branchProtectionRules: string
  branchSource: string
  branchSourceDesc: string
  branchTagCreation: string
  branchTagDeletion: string
  branchUpToDate: string
  branches: string
  browse: string
  browseFiles: string
  bySigningIn: string
  cancel: string
  changePassword: string
  changePasswordSuccesfully: string
  changeRole: string
  changes: string
  characterLimit: string
  checkRuns: string
  checkSuites: string
  checks: string
  clickHereToDownload: string
  clone: string
  cloneHTTPS: string
  cloneText: string
  close: string
  closed: string
  comment: string
  commentDeleted: string
  commit: string
  commitChanges: string
  commitDirectlyTo: string
  commitMessage: string
  commitString: string
  commitToNewBranch: string
  commits: string
  commitsOn: string
  compare: string
  compareEmptyDiffMessage: string
  compareEmptyDiffTitle: string
  comparingChanges: string
  confirm: string
  confirmDelete: string
  confirmDeleteWebhook: string
  confirmNewPassword: string
  confirmPassRequired: string
  confirmPassword: string
  confirmation: string
  content: string
  contents: string
  contributor: string
  conversation: string
  copy: string
  copyBranch: string
  copyCommitSHA: string
  create: string
  createABranch: string
  createATag: string
  createBranch: string
  createBranchFromBranch: string
  createBranchFromTag: string
  createFile: string
  createNewToken: string
  createNewUser: string
  createPullRequest: string
  createRepo: string
  'createRepoModal.branch': string
  'createRepoModal.branchLabel': string
  'createRepoModal.privateLabel': string
  'createRepoModal.publicLabel': string
  createRepoPerms: string
  createSpace: string
  createTag: string
  createWebhook: string
  created: string
  creationDate: string
  dangerDeleteRepo: string
  defaultBranch: string
  delete: string
  deleteBranch: string
  deleteBranchConfirm: string
  deleteCommentConfirm: string
  deleteFile: string
  deleteNotAllowed: string
  deleteRepoText: string
  deleteRepoTitle: string
  deleteSpace: string
  deleteTag: string
  deleteTagConfirm: string
  deleteToken: string
  deleteTokenMsg: string
  deleteUser: string
  deleted: string
  deployKeys: string
  descending: string
  description: string
  diff: string
  disableWebhookContent: string
  disableWebhookTitle: string
  displayName: string
  download: string
  draft: string
  edit: string
  editAsText: string
  editFile: string
  editNotAllowed: string
  editUser: string
  edited: string
  email: string
  emailRequired: string
  emptyRepoHeader: string
  emptyRepoInclude: string
  emptySpaceText: string
  enableSSLVerification: string
  enableWebhookContent: string
  enableWebhookTitle: string
  enabled: string
  enterBranchPlaceholder: string
  enterDescription: string
  enterName: string
  enterNewBranchName: string
  enterNewPassword: string
  enterRepoName: string
  enterSecret: string
  enterTagPlaceholder: string
  enterUser: string
  error: string
  error404Text: string
  'executions.name': string
  'executions.newExecutionButton': string
  'executions.noData': string
  executor: string
  existingAccount: string
  expiration: string
  expirationDate: string
  expired: string
  failed: string
  failedToCreateBranch: string
  failedToCreatePipeline: string
  failedToCreateRepo: string
  failedToCreateSpace: string
  failedToDeleteBranch: string
  failedToDeleteWebhook: string
  fileDeleted: string
  fileTooLarge: string
  files: string
  filesChanged: string
  findATag: string
  findAUser: string
  findBranch: string
  findOrCreateBranch: string
  firstTimeTitle: string
  general: string
  generateCloneCred: string
  generateCloneText: string
  getMyCloneTitle: string
  gitIgnore: string
  gitness: string
  help: string
  hideCommitHistory: string
  history: string
  'homepage.firstStep': string
  'homepage.welcomeText': string
  in: string
  inactiveBranches: string
  leaveAComment: string
  license: string
  lineBreaks: string
  loading: string
  logOut: string
  logoutMsg: string
  makeOptional: string
  makeRequired: string
  manageApiToken: string
  manageCredText: string
  matchPassword: string
  merged: string
  minPassLimit: string
  missingPerms: string
  missingPermsContent: string
  myComments: string
  nDays: string
  name: string
  nameYourBranch: string
  nameYourFile: string
  nameYourTag: string
  nameYourWebhook: string
  newFile: string
  newFileNotAllowed: string
  newFolder: string
  newMember: string
  newPullRequest: string
  newRepo: string
  newSpace: string
  newTag: string
  'newToken.expireOn': string
  'newToken.generateToken': string
  'newToken.namePlaceholder': string
  'newToken.text': string
  'newToken.tokenHelptext': string
  'newUserModal.displayNamePlaceholder': string
  'newUserModal.emailPlaceholder': string
  'newUserModal.passwordHelptext': string
  'newUserModal.uidPlaceholder': string
  'newUserModal.uidWarning': string
  'newUserModal.userCreated': string
  'newUserModal.userDeleted': string
  'newUserModal.userUpdated': string
  next: string
  noAccount: string
  'noAccount?': string
  noChanges: string
  noChangesCompare: string
  noChangesPR: string
  noCommits: string
  noCommitsMessage: string
  noCommitsPR: string
  noExpiration: string
  noExpirationDate: string
  noOptionalReviewers: string
  noRequiredReviewers: string
  noResultMessage: string
  noResultTitle: string
  noReviewers: string
  noWebHooks: string
  none: string
  noneYet: string
  off: string
  ok: string
  on: string
  onDate: string
  oneMustBeSelected: string
  open: string
  optional: string
  optionalExtendedDescription: string
  overview: string
  owner: string
  pageLoading: string
  pageNotFound: string
  'pageTitle.accessControl': string
  'pageTitle.branches': string
  'pageTitle.changePassword': string
  'pageTitle.commits': string
  'pageTitle.compare': string
  'pageTitle.createWebhook': string
  'pageTitle.editFile': string
  'pageTitle.executions': string
  'pageTitle.home': string
  'pageTitle.pipelines': string
  'pageTitle.pullRequest': string
  'pageTitle.pullRequests': string
  'pageTitle.register': string
  'pageTitle.repositories': string
  'pageTitle.repository': string
  'pageTitle.repositorySettings': string
  'pageTitle.secrets': string
  'pageTitle.signin': string
  'pageTitle.spaceSettings': string
  'pageTitle.tags': string
  'pageTitle.userProfile': string
  'pageTitle.users': string
  'pageTitle.webhookDetail': string
  'pageTitle.webhooks': string
  password: string
  passwordApi: string
  passwordRequired: string
  payloadUrl: string
  payloadUrlLabel: string
  pending: string
  'pipelines.name': string
  'pipelines.newPipelineButton': string
  'pipelines.noData': string
  'pr.ableToMerge': string
  'pr.addDescription': string
  'pr.authorCommentedPR': string
  'pr.branchHasNoConflicts': string
  'pr.cantBeMerged': string
  'pr.cantMerge': string
  'pr.checkingToMerge': string
  'pr.checks': string
  'pr.checksFailure': string
  'pr.createDraftPR': string
  'pr.descIsRequired': string
  'pr.descriptionPlaceHolder': string
  'pr.diffStatsLabel': string
  'pr.diffStatus': string
  'pr.diffView': string
  'pr.draftOpenForReview.desc': string
  'pr.draftOpenForReview.title': string
  'pr.enterDesc': string
  'pr.executionState': string
  'pr.failedToCreate': string
  'pr.failedToDeleteComment': string
  'pr.failedToSaveComment': string
  'pr.failedToUpdate': string
  'pr.failedToUpdateCommentStatus': string
  'pr.failedToUpdateTitle': string
  'pr.fileDeleted': string
  'pr.fileUnchanged': string
  'pr.mergeOptions.close': string
  'pr.mergeOptions.closeDesc': string
  'pr.mergeOptions.createMergeCommit': string
  'pr.mergeOptions.createMergeCommitDesc': string
  'pr.mergeOptions.rebaseAndMerge': string
  'pr.mergeOptions.rebaseAndMergeDesc': string
  'pr.mergeOptions.squashAndMerge': string
  'pr.mergeOptions.squashAndMergeDesc': string
  'pr.mergePR': string
  'pr.metaLine': string
  'pr.modalTitle': string
  'pr.openForReview': string
  'pr.outdated': string
  'pr.prBranchPushInfo': string
  'pr.prCanBeMerged': string
  'pr.prClosed': string
  'pr.prMerged': string
  'pr.prMergedBannerInfo': string
  'pr.prMergedInfo': string
  'pr.prReviewSubmit': string
  'pr.prStateChanged': string
  'pr.prStateChangedDraft': string
  'pr.readyForReview': string
  'pr.reviewChanges': string
  'pr.reviewSubmitted': string
  'pr.showDiff': string
  'pr.showLink': string
  'pr.split': string
  'pr.state': string
  'pr.status': string
  'pr.statusLine': string
  'pr.titleChanged': string
  'pr.titleChangedTable': string
  'pr.titleIsRequired': string
  'pr.titlePlaceHolder': string
  'pr.unified': string
  'prChecks.error': string
  'prChecks.failure': string
  'prChecks.notFound': string
  'prChecks.pending': string
  'prChecks.running': string
  'prChecks.success': string
  'prChecks.viewExternal': string
  prMustSelectSourceAndTargetBranches: string
  prSourceAndTargetMustBeDifferent: string
  'prState.draftDesc': string
  'prState.draftHeading': string
  prefixBase: string
  prefixCompare: string
  prev: string
  preview: string
  privacyPolicy: string
  private: string
  profile: string
  public: string
  pullMustBeMadeFromBranches: string
  pullRequestEmpty: string
  pullRequestalreadyExists: string
  pullRequests: string
  quote: string
  reactivate: string
  readMe: string
  reader: string
  refresh: string
  reject: string
  rejected: string
  remove: string
  removeAdmin: string
  renameFile: string
  reply: string
  replyAndReactivate: string
  replyAndResolve: string
  replyHere: string
  repoCloneHeader: string
  repoCloneLabel: string
  'repoDelete.deleteConfirm1': string
  'repoDelete.deleteConfirm2': string
  'repoDelete.deleteConfirmButton1': string
  'repoDelete.deleteConfirmButton2': string
  'repoDelete.deleteToastSuccess': string
  'repoDelete.title': string
  repoDeleted: string
  repoEmptyMarkdown: string
  repoEmptyMarkdownClone: string
  repoEmptyMarkdownClonePush: string
  repoEmptyMarkdownExisting: string
  repoUpdate: string
  'repos.activities': string
  'repos.data': string
  'repos.enterBranchName': string
  'repos.lastChange': string
  'repos.name': string
  'repos.noDataMessage': string
  'repos.updated': string
  repositories: string
  repositoryName: string
  requestChanges: string
  required: string
  resetZoom: string
  resolve: string
  resolved: string
  resolvedComments: string
  reviewerNotFound: string
  reviewers: string
  role: string
  running: string
  samplePayloadUrl: string
  save: string
  scanAlerts: string
  scrollToTop: string
  search: string
  searchBranches: string
  secret: string
  'secrets.createSecret': string
  'secrets.enterSecretName': string
  'secrets.failedToCreate': string
  'secrets.name': string
  'secrets.newSecretButton': string
  'secrets.noData': string
  'secrets.value': string
  selectBranchPlaceHolder: string
  selectRange: string
  selectSpace: string
  selectSpaceText: string
  selectToViewMore: string
  setAsAdmin: string
  settings: string
  showCommitHistory: string
  showEverything: string
  showLess: string
  showMore: string
  signIn: string
  signUp: string
  space: string
  'spaceMemberships.addMember': string
  'spaceMemberships.changeRole': string
  'spaceMemberships.memberAdded': string
  'spaceMemberships.memberUpdated': string
  'spaceMemberships.removeMember': string
  'spaceMemberships.removeMembershipMsg': string
  'spaceMemberships.removeMembershipToast': string
  'spaceSetting.deleteConfirm1': string
  'spaceSetting.deleteConfirm2': string
  'spaceSetting.deleteConfirmButton1': string
  'spaceSetting.deleteConfirmButton2': string
  'spaceSetting.deleteToastSuccess': string
  'spaceSetting.deleteWarning': string
  'spaceSetting.intentText': string
  'spaceSetting.setting': string
  spaces: string
  sslVerificationLabel: string
  status: string
  submitReview: string
  success: string
  switchBranchesTags: string
  tag: string
  tagCreated: string
  tagDeleted: string
  tagDescription: string
  tagEmpty: string
  tagNotFound: string
  tagger: string
  tags: string
  termsOfUse: string
  title: string
  token: string
  tooltipRepoEdit: string
  unrsolvedComment: string
  'unsavedChanges.leave': string
  'unsavedChanges.message': string
  'unsavedChanges.stay': string
  'unsavedChanges.title': string
  updateFile: string
  updateUser: string
  updateWebhook: string
  updated: string
  user: string
  userCreated: string
  userId: string
  'userManagement.deleteUser': string
  'userManagement.deleteUserMsg': string
  'userManagement.newUser': string
  'userManagement.removeAdminMsg': string
  'userManagement.resetPassword': string
  'userManagement.resetPasswordMsg': string
  'userManagement.setAsAdminMsg': string
  'userManagement.text': string
  userName: string
  userNameRequired: string
  'userProfile.deleteTokenMsg': string
  users: string
  'validation.confirmPasswordRequired': string
  'validation.emailInvalid': string
  'validation.emailRequired': string
  'validation.expirationDateRequired': string
  'validation.gitBranchNameInvalid': string
  'validation.gitTagNameInvalid': string
  'validation.nameInvalid': string
  'validation.nameIsRequired': string
  'validation.newPasswordRequired': string
  'validation.repoNamePatternIsNotValid': string
  'validation.spaceNamePatternIsNotValid': string
  'validation.uidInvalid': string
  'validation.uidRequired': string
  value: string
  viewAllBranches: string
  viewAllTags: string
  viewCommitDetails: string
  viewFile: string
  viewFiles: string
  viewRaw: string
  viewRepo: string
  viewed: string
  webhook: string
  webhookAllEventsSelected: string
  webhookBranchCreated: string
  webhookBranchDeleted: string
  webhookBranchUpdated: string
  webhookCreated: string
  webhookDeleted: string
  webhookDetails: string
  webhookDialogContent: string
  webhookDialogTitle: string
  webhookEmpty: string
  webhookEventsLabel: string
  webhookListingContent: string
  webhookPRBranchUpdated: string
  webhookPRCreated: string
  webhookPRReopened: string
  webhookSelectAllEvents: string
  webhookSelectIndividualEvents: string
  webhookSelectPushEvents: string
  webhookTagCreated: string
  webhookTagDeleted: string
  webhookTagUpdated: string
  webhookUpdated: string
  webhooks: string
  whatsNew: string
  write: string
  yourBranches: string
  yours: string
  zoomIn: string
  zoomOut: string
}
