/**
 * This file is auto-generated. Please do not modify this file manually.
 * Use the command `yarn strings` to regenerate this file.
 */
export interface StringsMap {
  active: string
  activeBranches: string
  add: string
  addComment: string
  addGitIgnore: string
  addLicense: string
  addNewFile: string
  addReadMe: string
  all: string
  allBranches: string
  allComments: string
  alreadyHaveAccount: string
  and: string
  approve: string
  ascending: string
  assignPeople: string
  basedOn: string
  blame: string
  blameCommitLine: string
  botAlerts: string
  branch: string
  branchCreated: string
  branchDeleted: string
  branchDivergenceAhead: string
  branchDivergenceAheadBehind: string
  branchDivergenceBehind: string
  branchDoesNotHaveFile: string
  branchName: string
  branchNotFound: string
  branchProtectionRules: string
  branchSource: string
  branchSourceDesc: string
  branchTagCreation: string
  branchTagDeletion: string
  branchUpToDate: string
  branches: string
  browse: string
  browseFiles: string
  bySigningIn: string
  cancel: string
  changes: string
  characterLimit: string
  checkRuns: string
  checkSuites: string
  checks: string
  clickHereToDownload: string
  clone: string
  cloneHTTPS: string
  cloneText: string
  closed: string
  comment: string
  commentDeleted: string
  commit: string
  commitChanges: string
  commitDirectlyTo: string
  commitMessage: string
  commitString: string
  commitToNewBranch: string
  commits: string
  commitsOn: string
  compare: string
  compareEmptyDiffMessage: string
  compareEmptyDiffTitle: string
  comparingChanges: string
  confirm: string
  confirmDelete: string
  confirmDeleteWebhook: string
  confirmation: string
  content: string
  contents: string
  conversation: string
  copy: string
  copyBranch: string
  copyCommitSHA: string
  create: string
  createABranch: string
  createATag: string
  createBranch: string
  createBranchFromBranch: string
  createBranchFromTag: string
  createFile: string
  createPullRequest: string
  createRepo: string
  'createRepoModal.branch': string
  'createRepoModal.branchLabel': string
  'createRepoModal.privateLabel': string
  'createRepoModal.publicLabel': string
  createRepoPerms: string
  createTag: string
  createWebhook: string
  creationDate: string
  dangerDeleteRepo: string
  defaultBranch: string
  delete: string
  deleteBranch: string
  deleteBranchConfirm: string
  deleteCommentConfirm: string
  deleteFile: string
  deleteNotAllowed: string
  deleteRepoText: string
  deleteRepoTitle: string
  deleteTag: string
  deleteTagConfirm: string
  deleted: string
  deployKeys: string
  descending: string
  description: string
  diff: string
  disableWebhookContent: string
  disableWebhookTitle: string
  download: string
  draft: string
  edit: string
  editFile: string
  editNotAllowed: string
  edited: string
  email: string
  emptyRepoHeader: string
  emptyRepoInclude: string
  enableSSLVerification: string
  enableWebhookContent: string
  enableWebhookTitle: string
  enabled: string
  enterDescription: string
  enterNewBranchName: string
  enterRepoName: string
  enterSecret: string
  enterTagPlaceholder: string
  enterUser: string
  error404Text: string
  existingAccount: string
  failedToCreateBranch: string
  failedToCreateRepo: string
  failedToDeleteBranch: string
  failedToDeleteWebhook: string
  fileDeleted: string
  fileTooLarge: string
  files: string
  filesChanged: string
  findATag: string
  findAUser: string
  findBranch: string
  findOrCreateBranch: string
  firstTimeTitle: string
  general: string
  generateCloneCred: string
  generateCloneText: string
  getMyCloneTitle: string
  gitIgnore: string
  help: string
  hideCommitHistory: string
  history: string
  in: string
  inactiveBranches: string
  leaveAComment: string
  license: string
  lineBreaks: string
  loading: string
  makeOptional: string
  makeRequired: string
  manageApiToken: string
  manageCredText: string
  merged: string
  missingPerms: string
  missingPermsContent: string
  myComments: string
  name: string
  nameYourBranch: string
  nameYourFile: string
  nameYourTag: string
  nameYourWebhook: string
  newFile: string
  newFileNotAllowed: string
  newFolder: string
  newPullRequest: string
  newRepo: string
  newTag: string
  next: string
  noAccount: string
  'noAccount?': string
  noChanges: string
  noChangesCompare: string
  noChangesPR: string
  noCommits: string
  noCommitsMessage: string
  noCommitsPR: string
  noOptionalReviewers: string
  noRequiredReviewers: string
  noResultMessage: string
  noResultTitle: string
  noReviewers: string
  noWebHooks: string
  none: string
  noneYet: string
  off: string
  ok: string
  on: string
  onDate: string
  oneMustBeSelected: string
  open: string
  optional: string
  optionalExtendedDescription: string
  overview: string
  pageLoading: string
  pageNotFound: string
  password: string
  passwordApi: string
  payloadUrl: string
  payloadUrlLabel: string
  pending: string
  'pr.ableToMerge': string
  'pr.authorCommentedPR': string
  'pr.branchHasNoConflicts': string
  'pr.cantBeMerged': string
  'pr.cantMerge': string
  'pr.checkingToMerge': string
  'pr.createDraftPR': string
  'pr.descIsRequired': string
  'pr.descriptionPlaceHolder': string
  'pr.diffStatsLabel': string
  'pr.diffStatus': string
  'pr.diffView': string
  'pr.draftOpenForReview.desc': string
  'pr.draftOpenForReview.title': string
  'pr.enterDesc': string
  'pr.executionState': string
  'pr.failedToCreate': string
  'pr.failedToDeleteComment': string
  'pr.failedToSaveComment': string
  'pr.failedToUpdate': string
  'pr.failedToUpdateCommentStatus': string
  'pr.failedToUpdateTitle': string
  'pr.fileDeleted': string
  'pr.fileUnchanged': string
  'pr.forceMergeWithUnresolvedComment': string
  'pr.mergeOptions.close': string
  'pr.mergeOptions.closeDesc': string
  'pr.mergeOptions.createMergeCommit': string
  'pr.mergeOptions.createMergeCommitDesc': string
  'pr.mergeOptions.rebaseAndMerge': string
  'pr.mergeOptions.rebaseAndMergeDesc': string
  'pr.mergeOptions.squashAndMerge': string
  'pr.mergeOptions.squashAndMergeDesc': string
  'pr.mergePR': string
  'pr.metaLine': string
  'pr.modalTitle': string
  'pr.notMergeableWithUnresolvedComment': string
  'pr.openForReview': string
  'pr.outdated': string
  'pr.prBranchPushInfo': string
  'pr.prCanBeMerged': string
  'pr.prClosed': string
  'pr.prMerged': string
  'pr.prMergedInfo': string
  'pr.prReviewSubmit': string
  'pr.prStateChanged': string
  'pr.prStateChangedDraft': string
  'pr.readyForReview': string
  'pr.reviewChanges': string
  'pr.reviewSubmitted': string
  'pr.showDiff': string
  'pr.showLink': string
  'pr.split': string
  'pr.state': string
  'pr.statusLine': string
  'pr.titleChanged': string
  'pr.titleChangedTable': string
  'pr.titleIsRequired': string
  'pr.titlePlaceHolder': string
  'pr.unified': string
  prMustSelectSourceAndTargetBranches: string
  prSourceAndTargetMustBeDifferent: string
  'prState.draftDesc': string
  'prState.draftHeading': string
  prefixBase: string
  prefixCompare: string
  prev: string
  preview: string
  privacyPolicy: string
  private: string
  public: string
  pullMustBeMadeFromBranches: string
  pullRequestEmpty: string
  pullRequestalreadyExists: string
  pullRequests: string
  quote: string
  reactivate: string
  readMe: string
  refresh: string
  reject: string
  rejected: string
  remove: string
  renameFile: string
  reply: string
  replyAndReactivate: string
  replyAndResolve: string
  replyHere: string
  repoCloneHeader: string
  repoCloneLabel: string
  repoDeleted: string
  repoEmptyMarkdown: string
  repoEmptyMarkdownClone: string
  repoEmptyMarkdownClonePush: string
  repoEmptyMarkdownExisting: string
  repoUpdate: string
  'repos.activities': string
  'repos.data': string
  'repos.enterBranchName': string
  'repos.lastChange': string
  'repos.name': string
  'repos.noDataMessage': string
  'repos.updated': string
  repositories: string
  repositoryName: string
  requestChanges: string
  required: string
  resetZoom: string
  resolve: string
  resolved: string
  resolvedComments: string
  reviewerNotFound: string
  reviewers: string
  samplePayloadUrl: string
  save: string
  scanAlerts: string
  scrollToTop: string
  search: string
  searchBranches: string
  secret: string
  selectBranchPlaceHolder: string
  selectToViewMore: string
  settings: string
  showCommitHistory: string
  showEverything: string
  signIn: string
  signUp: string
  spaces: string
  sslVerificationLabel: string
  status: string
  submitReview: string
  switchBranchesTags: string
  tag: string
  tagCreated: string
  tagDeleted: string
  tagDescription: string
  tagEmpty: string
  tagNotFound: string
  tagger: string
  tags: string
  termsOfUse: string
  title: string
  tooltipRepoEdit: string
  unrsolvedComment: string
  'unsavedChanges.leave': string
  'unsavedChanges.message': string
  'unsavedChanges.stay': string
  'unsavedChanges.title': string
  updateFile: string
  updateWebhook: string
  updated: string
  userId: string
  userName: string
  users: string
  'validation.gitBranchNameInvalid': string
  'validation.gitTagNameInvalid': string
  'validation.repoNamePatternIsNotValid': string
  viewAllBranches: string
  viewAllTags: string
  viewCommitDetails: string
  viewFile: string
  viewFiles: string
  viewRaw: string
  viewRepo: string
  viewed: string
  webhook: string
  webhookAllEventsSelected: string
  webhookBranchCreated: string
  webhookBranchDeleted: string
  webhookBranchUpdated: string
  webhookCreated: string
  webhookDeleted: string
  webhookDetails: string
  webhookDialogContent: string
  webhookDialogTitle: string
  webhookEmpty: string
  webhookEventsLabel: string
  webhookListingContent: string
  webhookPRBranchUpdated: string
  webhookPRCreated: string
  webhookPRReopened: string
  webhookSelectAllEvents: string
  webhookSelectIndividualEvents: string
  webhookSelectPushEvents: string
  webhookTagCreated: string
  webhookTagDeleted: string
  webhookTagUpdated: string
  webhookUpdated: string
  webhooks: string
  whatsNew: string
  write: string
  yourBranches: string
  yours: string
  zoomIn: string
  zoomOut: string
}
