FROM demoregistry.dataman-inc.com/library/centos7-base-git:20160705113509
MAINTAINER zwli zwli@dataman-inc.com

COPY drone/drone_static /
WORKDIR /
ENTRYPOINT ["/drone_static"]

#demoregistry.dataman-inc.com/shurenyun/centos7-drone:tag
