/* eslint-disable */
// This is an auto-generated file
export declare const active: string
export declare const chevron: string
export declare const consoleLine: string
export declare const content: string
export declare const expanded: string
export declare const forPipeline: string
export declare const header: string
export declare const headerLayout: string
export declare const hidden: string
export declare const invert: string
export declare const layout: string
export declare const main: string
export declare const markdown: string
export declare const markdownContainer: string
export declare const menu: string
export declare const menuItem: string
export declare const name: string
export declare const noShrink: string
export declare const pipelineStages: string
export declare const pipelineSteps: string
export declare const selected: string
export declare const spinner: string
export declare const status: string
export declare const stepHeader: string
export declare const stepLogViewer: string
export declare const subMenu: string
export declare const terminal: string
export declare const terminalContainer: string
export declare const text: string
export declare const uid: string
