ALTER TABLE infra_provider_configs ADD CONSTRAINT infra_provider_configs_ipconf_uid_ipconf_space_id_key UNIQUE (ipconf_uid, ipconf_space_id);
ALTER TABLE infra_provider_templates ADD CONSTRAINT infra_provider_templates_iptemp_uid_iptemp_space_id_key UNIQUE (iptemp_uid, iptemp_space_id);
ALTER TABLE infra_provider_resources ADD CONSTRAINT infra_provider_resources_ipreso_uid_ipreso_space_id_key UNIQUE (ipreso_uid, ipreso_space_id);
ALTER TABLE gitspace_configs ADD CONSTRAINT gitspace_configs_gconf_uid_gconf_space_id_key UNIQUE (gconf_uid, gconf_space_id);
ALTER TABLE gitspaces ADD CONSTRAINT gitspaces_gits_gitspace_config_id_gits_space_id_key UNIQUE (gits_gitspace_config_id, gits_space_id);
DROP INDEX infra_provider_configs_uid_space_id ;
DROP INDEX infra_provider_templates_uid_space_id;
DROP INDEX infra_provider_resources_uid_space_id;
DROP INDEX gitspace_configs_uid_space_id;
DROP INDEX gitspaces_gitspace_config_id_space_id;

ALTER TABLE infra_provider_configs RENAME COLUMN ipconf_display_name TO ipconf_name;
ALTER TABLE infra_provider_resources RENAME COLUMN ipreso_display_name TO ipreso_name;
ALTER TABLE gitspace_configs RENAME COLUMN gconf_display_name TO gconf_name;