#!/bin/sh
set -e

case "$1" in
  abort-upgrade|abort-remove|abort-deconfigure|configure)
    ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

echo "Starting drone ..."
if [ -f /etc/init/drone.conf ]; then
    if pidof /usr/local/bin/drone >/dev/null; then
        service drone stop || exit $?
    fi
    service drone start && echo "Drone started."
fi

#DEBHELPER#

exit 0
