#!/bin/sh

set -e
set -u

case "$1" in
  remove|remove-in-favour|deconfigure|deconfigure-in-favour)
    if [ -f /etc/init/drone.conf ]; then
      echo "Stopping drone ..."
      service drone stop || exit $?
      echo "Drone Stopped."
    fi
    ;;

  upgrade|failed-upgrade)
    ;;

  *)
    echo "prerm called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

#DEBHELPER#

exit 0
