/**
 * Copyright 2022 Harness Inc. All rights reserved.
 * Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
 * that can be found in the licenses directory at the root of this repository, also available at
 * https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.
 */

/**
 * This file is auto-generated. Please do not modify this file manually.
 * Use the command `yarn strings` to regenerate this file.
 */
export interface StringsMap {
  'artifactDetails.artifactLabelInputPlaceholder': string
  'artifactDetails.downloadsThisWeek': string
  'artifactDetails.labelsUpdated': string
  'artifactDetails.page': string
  'artifactList.deployedArtifacts': string
  'artifactList.page': string
  'artifactList.pageHeading': string
  'artifactList.table.actions.VulnerabilityStatus.digestMenuItemText': string
  'artifactList.table.actions.VulnerabilityStatus.nonScanned': string
  'artifactList.table.actions.VulnerabilityStatus.partiallyScanned': string
  'artifactList.table.actions.VulnerabilityStatus.scanStatus': string
  'artifactList.table.actions.VulnerabilityStatus.scanned': string
  'artifactList.table.actions.deleteRepository': string
  'artifactList.table.actions.editRepository': string
  'artifactList.table.allRepositories': string
  'artifactList.table.allVersions': string
  'artifactList.table.columns.artifactName': string
  'artifactList.table.columns.downloads': string
  'artifactList.table.columns.environments': string
  'artifactList.table.columns.lastUpdated': string
  'artifactList.table.columns.latestVersion': string
  'artifactList.table.columns.name': string
  'artifactList.table.columns.pullCommand': string
  'artifactList.table.columns.repository': string
  'artifactList.table.columns.sto': string
  'artifactList.table.columns.tags': string
  'artifactList.table.latestVersions': string
  'artifactList.table.noArtifactsTitle': string
  'digestList.page': string
  'digestList.table.aboutDigest': string
  'digestList.table.columns.digest': string
  'digestList.table.columns.downloads': string
  'digestList.table.columns.osArch': string
  'digestList.table.columns.scanStatus': string
  'digestList.table.columns.size': string
  'digestList.table.columns.uploadedBy': string
  'digestList.table.noDigestTitle': string
  'repositoryDetails.clientSetup.done': string
  'repositoryDetails.clientSetup.failedToGenerateToken': string
  'repositoryDetails.clientSetup.generateNewToken': string
  'repositoryDetails.clientSetup.generateToken': string
  'repositoryDetails.clientSetup.step': string
  'repositoryDetails.repositoryForm.addPatterns': string
  'repositoryDetails.repositoryForm.advancedOptionsTitle': string
  'repositoryDetails.repositoryForm.cleanupPoliciesSubTitle': string
  'repositoryDetails.repositoryForm.cleanupPoliciesTitle': string
  'repositoryDetails.repositoryForm.create': string
  'repositoryDetails.repositoryForm.enterpriseAdvancedOptionsSubTitle': string
  'repositoryDetails.repositoryForm.environment': string
  'repositoryDetails.repositoryForm.environmentPlaceholder': string
  'repositoryDetails.repositoryForm.excludePatternsLabel': string
  'repositoryDetails.repositoryForm.excludePatternsPlaceholder': string
  'repositoryDetails.repositoryForm.includeExcludePatternsSubTitle': string
  'repositoryDetails.repositoryForm.includeExcludePatternsTitle': string
  'repositoryDetails.repositoryForm.includePatternsLabel': string
  'repositoryDetails.repositoryForm.includePatternsPlaceholder': string
  'repositoryDetails.repositoryForm.modalSubTitle': string
  'repositoryDetails.repositoryForm.modalTitle': string
  'repositoryDetails.repositoryForm.name': string
  'repositoryDetails.repositoryForm.nameRequired': string
  'repositoryDetails.repositoryForm.newEnvironment': string
  'repositoryDetails.repositoryForm.newExcludePattern': string
  'repositoryDetails.repositoryForm.newIncludePattern': string
  'repositoryDetails.repositoryForm.newUpstreamProxy': string
  'repositoryDetails.repositoryForm.ossAdvancedOptionsSubTitle': string
  'repositoryDetails.repositoryForm.repositoryCreated': string
  'repositoryDetails.repositoryForm.repositoryDeleted': string
  'repositoryDetails.repositoryForm.repositoryUpdated': string
  'repositoryDetails.repositoryForm.selectRepoType': string
  'repositoryDetails.repositoryForm.title': string
  'repositoryDetails.repositoryForm.upstreamProxiesSubTitle': string
  'repositoryDetails.repositoryForm.upstreamProxiesTitle': string
  'repositoryDetails.tabs.configuration': string
  'repositoryDetails.tabs.packages': string
  'repositoryDetails.upstreamProxiesSelectList.addUpstreamProxies': string
  'repositoryDetails.upstreamProxiesSelectList.newUpstreamProxyLabel': string
  'repositoryDetails.upstreamProxiesSelectList.selectList.Title': string
  'repositoryDetails.upstreamProxiesSelectList.selectedList.Title': string
  'repositoryDetails.upstreamProxiesSelectList.selectedList.note.label': string
  'repositoryDetails.upstreamProxiesSelectList.selectedList.note.message': string
  'repositoryList.artifactRegistry.label': string
  'repositoryList.artifactRegistry.subLabel': string
  'repositoryList.deleteModal.contentText': string
  'repositoryList.deleteModal.title': string
  'repositoryList.newRegistry': string
  'repositoryList.newRepository': string
  'repositoryList.pageHeading': string
  'repositoryList.selectEnvironments': string
  'repositoryList.selectLabels': string
  'repositoryList.selectPackageTypes': string
  'repositoryList.table.columns.artifacts': string
  'repositoryList.table.columns.downloads': string
  'repositoryList.table.columns.lastModified': string
  'repositoryList.table.columns.nameAndEnvironment': string
  'repositoryList.table.columns.size': string
  'repositoryList.table.columns.type': string
  'repositoryList.table.columns.upstreamProxies': string
  'repositoryList.table.columns.url': string
  'repositoryList.table.copyRegistryUrl': string
  'repositoryList.table.copyUpstreamUrl': string
  'repositoryList.table.copyUrl': string
  'repositoryList.table.noRepositoriesTitle': string
  'repositoryList.upstreamProxy.label': string
  'repositoryList.upstreamProxy.subLabel': string
  'upstreamProxyDetails.actions.createUpdateModal.createSuccessMessage': string
  'upstreamProxyDetails.actions.createUpdateModal.updateSuccessMessage': string
  'upstreamProxyDetails.actions.delete.contentText': string
  'upstreamProxyDetails.actions.delete.repositoryDeleted': string
  'upstreamProxyDetails.actions.delete.title': string
  'upstreamProxyDetails.createForm.authentication.anonymous': string
  'upstreamProxyDetails.createForm.authentication.anonymousSubLabel': string
  'upstreamProxyDetails.createForm.authentication.password': string
  'upstreamProxyDetails.createForm.authentication.title': string
  'upstreamProxyDetails.createForm.authentication.userNameAndPassword': string
  'upstreamProxyDetails.createForm.authentication.username': string
  'upstreamProxyDetails.createForm.create': string
  'upstreamProxyDetails.createForm.key': string
  'upstreamProxyDetails.createForm.packageType': string
  'upstreamProxyDetails.createForm.source.custom': string
  'upstreamProxyDetails.createForm.source.dockerHub': string
  'upstreamProxyDetails.createForm.source.title': string
  'upstreamProxyDetails.createForm.title': string
  'upstreamProxyDetails.createForm.url': string
  'upstreamProxyDetails.createForm.urlPlaceholder': string
  'upstreamProxyDetails.editForm.title': string
  'upstreamProxyDetails.editForm.update': string
  'upstreamProxyDetails.form.title': string
  'upstreamProxyDetails.page': string
  'versionDetails.artifactDetails.layers.archSelectLabel': string
  'versionDetails.artifactDetails.layers.archSelectPlaceholder': string
  'versionDetails.artifactDetails.layers.digest': string
  'versionDetails.artifactDetails.layers.imageLayers': string
  'versionDetails.artifactDetails.layers.lastPush': string
  'versionDetails.artifactDetails.layers.size': string
  'versionDetails.artifactDetails.tabs.layers': string
  'versionDetails.artifactDetails.tabs.manifest': string
  'versionDetails.cards.container.title': string
  'versionDetails.cards.container.versionDigest': string
  'versionDetails.cards.deploymentsCard.buildTitle': string
  'versionDetails.cards.deploymentsCard.executionId': string
  'versionDetails.cards.deploymentsCard.title': string
  'versionDetails.cards.securityTests.critical': string
  'versionDetails.cards.securityTests.high': string
  'versionDetails.cards.securityTests.ignored': string
  'versionDetails.cards.securityTests.info': string
  'versionDetails.cards.securityTests.low': string
  'versionDetails.cards.securityTests.medium': string
  'versionDetails.cards.securityTests.title': string
  'versionDetails.cards.securityTests.totalCount': string
  'versionDetails.cards.supplyChain.allowList': string
  'versionDetails.cards.supplyChain.denyListViolation': string
  'versionDetails.cards.supplyChain.sbomScore': string
  'versionDetails.cards.supplyChain.slsaProvenance': string
  'versionDetails.cards.supplyChain.title': string
  'versionDetails.cards.supplyChain.totalComponents': string
  'versionDetails.deploymentsTable.columns.deploymentPipeline': string
  'versionDetails.deploymentsTable.columns.environment': string
  'versionDetails.deploymentsTable.columns.services': string
  'versionDetails.deploymentsTable.columns.triggeredBy': string
  'versionDetails.deploymentsTable.columns.type': string
  'versionDetails.deploymentsTable.noDeploymentsTitle': string
  'versionDetails.overview.generalInformation.createdAndLastModifiedAt': string
  'versionDetails.overview.generalInformation.description': string
  'versionDetails.overview.generalInformation.downloads': string
  'versionDetails.overview.generalInformation.name': string
  'versionDetails.overview.generalInformation.packageType': string
  'versionDetails.overview.generalInformation.pullCommand': string
  'versionDetails.overview.generalInformation.repositoryPath': string
  'versionDetails.overview.generalInformation.size': string
  'versionDetails.overview.generalInformation.title': string
  'versionDetails.overview.generalInformation.uploadedBy': string
  'versionDetails.overview.generalInformation.url': string
  'versionDetails.overview.generalInformation.version': string
  'versionDetails.page': string
  'versionDetails.tabs.artifactDetails': string
  'versionDetails.tabs.code': string
  'versionDetails.tabs.deployments': string
  'versionDetails.tabs.overview': string
  'versionDetails.tabs.securityTests': string
  'versionDetails.tabs.supplyChain': string
  'versionList.actions.deleteModal.contentText': string
  'versionList.actions.deleteModal.title': string
  'versionList.page': string
  'versionList.table.columns.activelyDeployed': string
  'versionList.table.columns.deployments': string
  'versionList.table.columns.digests': string
  'versionList.table.columns.downloads': string
  'versionList.table.columns.publishedByAt': string
  'versionList.table.columns.pullCommand': string
  'versionList.table.columns.size': string
  'versionList.table.columns.version': string
  'versionList.table.noVersionsTitle': string
  'actions.delete': string
  'actions.edit': string
  'actions.quarantine': string
  'actions.restore': string
  'actions.scan': string
  'actions.setupClient': string
  add: string
  'badges.artifactRegistry': string
  'badges.upstreamProxy': string
  'breadcrumbs.artifacts': string
  'breadcrumbs.repositories': string
  'breadcrumbs.upstreamProxies': string
  cancel: string
  'cleanupPolicy.addBtn': string
  'cleanupPolicy.addPattern': string
  'cleanupPolicy.cleanUpByArtifactsOlderThan': string
  'cleanupPolicy.cleanUpByArtifactsOlderThanPlaceholder': string
  'cleanupPolicy.cleanUpByPackagePrefixes': string
  'cleanupPolicy.cleanUpByTagPrefixes': string
  'cleanupPolicy.cleanUpByVersionPrefixes': string
  'cleanupPolicy.infoMessage': string
  'cleanupPolicy.name': string
  'cleanupPolicy.placeholder': string
  clearFilters: string
  copied: string
  copy: string
  createdAt: string
  dateLabel: string
  delete: string
  description: string
  descriptionPlaceholder: string
  discard: string
  download: string
  enterPlaceholder: string
  failedToLoadData: string
  harLabel: string
  harnessAI: string
  id: string
  lastUpdated: string
  modifiedAt: string
  moduleName: string
  na: string
  new: string
  noDescription: string
  noMatchingFilterData: string
  noResultsFound: string
  nonProd: string
  nonProdCount: string
  optionalField: string
  'packageTypes.dockerPackage': string
  'packageTypes.helmPackage': string
  plusNewName: string
  prod: string
  prodCount: string
  'repositoryTypes.docker': string
  'repositoryTypes.generic': string
  'repositoryTypes.gradle': string
  'repositoryTypes.helm': string
  'repositoryTypes.maven': string
  'repositoryTypes.npm': string
  'repositoryTypes.nuget': string
  'repositoryTypes.pypi': string
  save: string
  search: string
  'sideNav.artifacts': string
  'sideNav.repositories': string
  'sideNav.upstreamProxies': string
  stepNotFound: string
  tabNotFound: string
  'tags.latest': string
  'tags.latestVersion': string
  tagsLabel: string
  timeLabel: string
  'validationMessages.cleanupPolicy.expireDaysRequired': string
  'validationMessages.cleanupPolicy.nameRequired': string
  'validationMessages.cleanupPolicy.positiveExpireDays': string
  'validationMessages.nameRequired': string
  'validationMessages.passwordRequired': string
  'validationMessages.repokeyRegExMessage': string
  'validationMessages.urlPattern': string
  'validationMessages.urlRequired': string
  'validationMessages.userNameRequired': string
}
