/**
 * Copyright 2022 Harness Inc. All rights reserved.
 * Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
 * that can be found in the licenses directory at the root of this repository, also available at
 * https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.
 */

/**
 * This file is auto-generated. Please do not modify this file manually.
 * Use the command `yarn strings` to regenerate this file.
 */
export interface StringsMap {
  'artifactDetails.artifactDeleted': string
  'artifactDetails.artifactLabelInputPlaceholder': string
  'artifactDetails.createdAsyncDownloadRequest': string
  'artifactDetails.deleteModal.contentText': string
  'artifactDetails.deleteModal.inputLabel': string
  'artifactDetails.deleteModal.inputPlaceholder': string
  'artifactDetails.deleteModal.title': string
  'artifactDetails.downloadsThisWeek': string
  'artifactDetails.labelsUpdated': string
  'artifactDetails.packageArchived': string
  'artifactDetails.page': string
  'artifactDetails.restoreModal.contentText': string
  'artifactDetails.restoreModal.inputLabel': string
  'artifactDetails.restoreModal.inputPlaceholder': string
  'artifactDetails.restoreModal.title': string
  'artifactDetails.softDeleteModal.contentText': string
  'artifactDetails.softDeleteModal.inputLabel': string
  'artifactDetails.softDeleteModal.inputPlaceholder': string
  'artifactDetails.softDeleteModal.title': string
  'artifactDetails.tabs.properties': string
  'artifactDetails.tabs.versions': string
  'artifactDetails.totalDownloads': string
  'artifactList.deployedArtifacts': string
  'artifactList.page': string
  'artifactList.pageHeading': string
  'artifactList.table.actions.VulnerabilityStatus.digestMenuItemText': string
  'artifactList.table.actions.VulnerabilityStatus.nonScanned': string
  'artifactList.table.actions.VulnerabilityStatus.partiallyScanned': string
  'artifactList.table.actions.VulnerabilityStatus.scanStatus': string
  'artifactList.table.actions.VulnerabilityStatus.scanned': string
  'artifactList.table.actions.archivePackage': string
  'artifactList.table.actions.deleteArtifact': string
  'artifactList.table.actions.deleteRepository': string
  'artifactList.table.actions.download': string
  'artifactList.table.actions.editRepository': string
  'artifactList.table.actions.restorePackage': string
  'artifactList.table.allRepositories': string
  'artifactList.table.allVersions': string
  'artifactList.table.columns.archivedAt': string
  'artifactList.table.columns.artifactName': string
  'artifactList.table.columns.downloads': string
  'artifactList.table.columns.environments': string
  'artifactList.table.columns.lastUpdated': string
  'artifactList.table.columns.latestVersion': string
  'artifactList.table.columns.name': string
  'artifactList.table.columns.pullCommand': string
  'artifactList.table.columns.repository': string
  'artifactList.table.columns.size': string
  'artifactList.table.columns.sto': string
  'artifactList.table.columns.tags': string
  'artifactList.table.columns.type': string
  'artifactList.table.columns.version': string
  'artifactList.table.latestVersions': string
  'artifactList.table.noArchivedArtifactsTitle': string
  'artifactList.table.noArtifactsTitle': string
  'artifactList.viewArtifactDetails': string
  'dependencyFirewall.page': string
  'dependencyFirewall.pageHeading': string
  'dependencyFirewall.tabs.exceptions': string
  'dependencyFirewall.tabs.violations': string
  'digestList.page': string
  'digestList.table.aboutDigest': string
  'digestList.table.columns.digest': string
  'digestList.table.columns.downloads': string
  'digestList.table.columns.osArch': string
  'digestList.table.columns.scanStatus': string
  'digestList.table.columns.size': string
  'digestList.table.columns.uploadedBy': string
  'digestList.table.noDigestTitle': string
  'labelsList.canbeAddedByUsers': string
  'labelsList.createLabelModal.actions.cancel': string
  'labelsList.createLabelModal.actions.create': string
  'labelsList.createLabelModal.labelCreated': string
  'labelsList.createLabelModal.title': string
  'labelsList.defaultLabelName': string
  'labelsList.deleteLabelModal.contentText': string
  'labelsList.deleteLabelModal.labelDeleted': string
  'labelsList.deleteLabelModal.title': string
  'labelsList.labelForm.description': string
  'labelsList.labelForm.dynamic': string
  'labelsList.labelForm.name': string
  'labelsList.labelForm.newValue': string
  'labelsList.labelForm.preview': string
  'labelsList.labelForm.value': string
  'labelsList.labelForm.values': string
  'labelsList.table.actions.delete': string
  'labelsList.table.actions.edit': string
  'labelsList.table.columns.associations': string
  'labelsList.table.columns.description': string
  'labelsList.table.columns.name': string
  'labelsList.table.columns.scope': string
  'labelsList.table.newLabel': string
  'labelsList.table.noData': string
  'labelsList.updateLabelModal.actions.cancel': string
  'labelsList.updateLabelModal.actions.update': string
  'labelsList.updateLabelModal.labelUpdated': string
  'labelsList.updateLabelModal.title': string
  'manageRegistries.comingSoon': string
  'manageRegistries.pageHeading': string
  'manageRegistries.tabs.cleanup_policies': string
  'manageRegistries.tabs.labels': string
  'repositoryDetails.clientSetup.done': string
  'repositoryDetails.clientSetup.failedToGenerateToken': string
  'repositoryDetails.clientSetup.generateNewToken': string
  'repositoryDetails.clientSetup.generateToken': string
  'repositoryDetails.clientSetup.step': string
  'repositoryDetails.registries': string
  'repositoryDetails.repositoryForm.addPatterns': string
  'repositoryDetails.repositoryForm.advancedOptionsTitle': string
  'repositoryDetails.repositoryForm.cleanupPoliciesSubTitle': string
  'repositoryDetails.repositoryForm.cleanupPoliciesTitle': string
  'repositoryDetails.repositoryForm.create': string
  'repositoryDetails.repositoryForm.enterpriseAdvancedOptionsSubTitle': string
  'repositoryDetails.repositoryForm.enterpriseAdvancedWithoutUpstreamOptionsSubTitle': string
  'repositoryDetails.repositoryForm.environment': string
  'repositoryDetails.repositoryForm.environmentPlaceholder': string
  'repositoryDetails.repositoryForm.excludePatternsLabel': string
  'repositoryDetails.repositoryForm.excludePatternsPlaceholder': string
  'repositoryDetails.repositoryForm.includeExcludePatternsSubTitle': string
  'repositoryDetails.repositoryForm.includeExcludePatternsTitle': string
  'repositoryDetails.repositoryForm.includePatternsLabel': string
  'repositoryDetails.repositoryForm.includePatternsPlaceholder': string
  'repositoryDetails.repositoryForm.modalSubTitle': string
  'repositoryDetails.repositoryForm.modalTitle': string
  'repositoryDetails.repositoryForm.name': string
  'repositoryDetails.repositoryForm.nameRequired': string
  'repositoryDetails.repositoryForm.newEnvironment': string
  'repositoryDetails.repositoryForm.newExcludePattern': string
  'repositoryDetails.repositoryForm.newIncludePattern': string
  'repositoryDetails.repositoryForm.newUpstreamProxy': string
  'repositoryDetails.repositoryForm.opaPolicy.addTitle': string
  'repositoryDetails.repositoryForm.opaPolicy.subTitle': string
  'repositoryDetails.repositoryForm.opaPolicy.title': string
  'repositoryDetails.repositoryForm.ossAdvancedOptionsSubTitle': string
  'repositoryDetails.repositoryForm.repositoryCreated': string
  'repositoryDetails.repositoryForm.repositoryDeleted': string
  'repositoryDetails.repositoryForm.repositoryRestored': string
  'repositoryDetails.repositoryForm.repositorySoftDeleted': string
  'repositoryDetails.repositoryForm.repositoryUpdated': string
  'repositoryDetails.repositoryForm.securityScan.containerScannerSelect.cardSubTitle': string
  'repositoryDetails.repositoryForm.securityScan.containerScannerSelect.cardTitle': string
  'repositoryDetails.repositoryForm.securityScan.containerScannerSelect.scannerNoteForRequiredConfiguration': string
  'repositoryDetails.repositoryForm.securityScan.containerScannerSelect.scannerNoteForRequiredLicense': string
  'repositoryDetails.repositoryForm.securityScan.title': string
  'repositoryDetails.repositoryForm.selectRepoType': string
  'repositoryDetails.repositoryForm.title': string
  'repositoryDetails.repositoryForm.upstreamProxiesSubTitle': string
  'repositoryDetails.repositoryForm.upstreamProxiesSubTitleWithLocalSupport': string
  'repositoryDetails.repositoryForm.upstreamProxiesSubTitleWithLocalSupportNote': string
  'repositoryDetails.repositoryForm.upstreamProxiesTitle': string
  'repositoryDetails.repositoryForm.visibility.private': string
  'repositoryDetails.repositoryForm.visibility.privateDescription': string
  'repositoryDetails.repositoryForm.visibility.public': string
  'repositoryDetails.repositoryForm.visibility.publicDescription': string
  'repositoryDetails.repositoryForm.visibility.title': string
  'repositoryDetails.tabs.configuration': string
  'repositoryDetails.tabs.datasets': string
  'repositoryDetails.tabs.models': string
  'repositoryDetails.tabs.packages': string
  'repositoryDetails.tabs.properties': string
  'repositoryDetails.tabs.webhooks': string
  'repositoryDetails.upstream': string
  'repositoryDetails.upstreamProxiesSelectList.addUpstreamProxies': string
  'repositoryDetails.upstreamProxiesSelectList.newUpstreamProxyLabel': string
  'repositoryDetails.upstreamProxiesSelectList.selectList.Title': string
  'repositoryDetails.upstreamProxiesSelectList.selectedList.Title': string
  'repositoryDetails.upstreamProxiesSelectList.selectedList.note.label': string
  'repositoryDetails.upstreamProxiesSelectList.selectedList.note.message': string
  'repositoryDetails.virtual': string
  'repositoryList.artifactRegistry.label': string
  'repositoryList.artifactRegistry.subLabel': string
  'repositoryList.compact': string
  'repositoryList.deleteModal.contentText': string
  'repositoryList.deleteModal.inputLabel': string
  'repositoryList.deleteModal.inputPlaceholder': string
  'repositoryList.deleteModal.title': string
  'repositoryList.newRegistry': string
  'repositoryList.newRepository': string
  'repositoryList.pageHeading': string
  'repositoryList.registryCount': string
  'repositoryList.restoreModal.contentText': string
  'repositoryList.restoreModal.inputLabel': string
  'repositoryList.restoreModal.inputPlaceholder': string
  'repositoryList.restoreModal.title': string
  'repositoryList.scope.accountOnly': string
  'repositoryList.scope.accountRecursive': string
  'repositoryList.scope.orgOnly': string
  'repositoryList.scope.orgRecursive': string
  'repositoryList.selectEnvironments': string
  'repositoryList.selectLabels': string
  'repositoryList.selectPackageTypes': string
  'repositoryList.selectRegistryType': string
  'repositoryList.selectScope': string
  'repositoryList.softDeleteModal.contentText': string
  'repositoryList.softDeleteModal.inputLabel': string
  'repositoryList.softDeleteModal.inputPlaceholder': string
  'repositoryList.softDeleteModal.title': string
  'repositoryList.table.columns.archivedAt': string
  'repositoryList.table.columns.artifacts': string
  'repositoryList.table.columns.downloads': string
  'repositoryList.table.columns.lastModified': string
  'repositoryList.table.columns.nameAndEnvironment': string
  'repositoryList.table.columns.size': string
  'repositoryList.table.columns.type': string
  'repositoryList.table.columns.upstreamProxies': string
  'repositoryList.table.columns.url': string
  'repositoryList.table.copyRegistryUrl': string
  'repositoryList.table.copyUpstreamUrl': string
  'repositoryList.table.copyUrl': string
  'repositoryList.table.noArchivedRepositoriesTitle': string
  'repositoryList.table.noRepositoriesTitle': string
  'repositoryList.upstreamProxy.label': string
  'repositoryList.upstreamProxy.subLabel': string
  'upstreamProxyDetails.actions.createUpdateModal.createSuccessMessage': string
  'upstreamProxyDetails.actions.createUpdateModal.updateSuccessMessage': string
  'upstreamProxyDetails.actions.delete.contentText': string
  'upstreamProxyDetails.actions.delete.inputLabel': string
  'upstreamProxyDetails.actions.delete.inputPlaceholder': string
  'upstreamProxyDetails.actions.delete.repositoryDeleted': string
  'upstreamProxyDetails.actions.delete.title': string
  'upstreamProxyDetails.createForm.authentication.accessKey': string
  'upstreamProxyDetails.createForm.authentication.accessKeyAndSecretKey': string
  'upstreamProxyDetails.createForm.authentication.anonymous': string
  'upstreamProxyDetails.createForm.authentication.anonymousSubLabel': string
  'upstreamProxyDetails.createForm.authentication.password': string
  'upstreamProxyDetails.createForm.authentication.secretKey': string
  'upstreamProxyDetails.createForm.authentication.title': string
  'upstreamProxyDetails.createForm.authentication.userNameAndPassword': string
  'upstreamProxyDetails.createForm.authentication.username': string
  'upstreamProxyDetails.createForm.create': string
  'upstreamProxyDetails.createForm.customRegistrySuffix': string
  'upstreamProxyDetails.createForm.customRegistrySuffixPlaceholder': string
  'upstreamProxyDetails.createForm.key': string
  'upstreamProxyDetails.createForm.packageType': string
  'upstreamProxyDetails.createForm.source.bioconda': string
  'upstreamProxyDetails.createForm.source.crates': string
  'upstreamProxyDetails.createForm.source.custom': string
  'upstreamProxyDetails.createForm.source.dockerHub': string
  'upstreamProxyDetails.createForm.source.ecr': string
  'upstreamProxyDetails.createForm.source.goproxy': string
  'upstreamProxyDetails.createForm.source.huggingface': string
  'upstreamProxyDetails.createForm.source.mavenCentral': string
  'upstreamProxyDetails.createForm.source.npmjs': string
  'upstreamProxyDetails.createForm.source.nugetOrg': string
  'upstreamProxyDetails.createForm.source.packagist': string
  'upstreamProxyDetails.createForm.source.pubdev': string
  'upstreamProxyDetails.createForm.source.pypi': string
  'upstreamProxyDetails.createForm.source.title': string
  'upstreamProxyDetails.createForm.title': string
  'upstreamProxyDetails.createForm.url': string
  'upstreamProxyDetails.createForm.urlPlaceholder': string
  'upstreamProxyDetails.editForm.enterpriseAdvancedOptionsSubTitle': string
  'upstreamProxyDetails.editForm.title': string
  'upstreamProxyDetails.editForm.update': string
  'upstreamProxyDetails.form.title': string
  'upstreamProxyDetails.page': string
  'versionDetails.OCIVersionSelectorTab.digest': string
  'versionDetails.OCIVersionSelectorTab.tag': string
  'versionDetails.artifactDetails.layers.archSelectLabel': string
  'versionDetails.artifactDetails.layers.archSelectPlaceholder': string
  'versionDetails.artifactDetails.layers.digest': string
  'versionDetails.artifactDetails.layers.imageLayers': string
  'versionDetails.artifactDetails.layers.lastPush': string
  'versionDetails.artifactDetails.layers.size': string
  'versionDetails.artifactDetails.tabs.dependencies': string
  'versionDetails.artifactDetails.tabs.files': string
  'versionDetails.artifactDetails.tabs.layers': string
  'versionDetails.artifactDetails.tabs.manifest': string
  'versionDetails.artifactDetails.tabs.readme': string
  'versionDetails.artifactFiles.table.columns.checksum': string
  'versionDetails.artifactFiles.table.columns.created': string
  'versionDetails.artifactFiles.table.columns.downloadCommand': string
  'versionDetails.artifactFiles.table.columns.name': string
  'versionDetails.artifactFiles.table.columns.size': string
  'versionDetails.cards.container.title': string
  'versionDetails.cards.container.versionDigest': string
  'versionDetails.cards.deploymentsCard.buildTitle': string
  'versionDetails.cards.deploymentsCard.executionId': string
  'versionDetails.cards.deploymentsCard.title': string
  'versionDetails.cards.securityTests.critical': string
  'versionDetails.cards.securityTests.high': string
  'versionDetails.cards.securityTests.ignored': string
  'versionDetails.cards.securityTests.info': string
  'versionDetails.cards.securityTests.low': string
  'versionDetails.cards.securityTests.medium': string
  'versionDetails.cards.securityTests.title': string
  'versionDetails.cards.securityTests.totalIssues': string
  'versionDetails.cards.slsaCard.provenanceDataNotAvailable': string
  'versionDetails.cards.slsaCard.slsaProvenance': string
  'versionDetails.cards.slsaCard.slsaVerificationStatus': string
  'versionDetails.cards.slsaCard.title': string
  'versionDetails.cards.supplyChain.SBOMDataNotAvailable': string
  'versionDetails.cards.supplyChain.allowList': string
  'versionDetails.cards.supplyChain.denyListViolation': string
  'versionDetails.cards.supplyChain.downloadSbom': string
  'versionDetails.cards.supplyChain.sbomScore': string
  'versionDetails.cards.supplyChain.title': string
  'versionDetails.cards.supplyChain.totalComponents': string
  'versionDetails.deleteVersionModal.contentText': string
  'versionDetails.deleteVersionModal.inputLabel': string
  'versionDetails.deleteVersionModal.inputPlaceholder': string
  'versionDetails.deleteVersionModal.title': string
  'versionDetails.dependencyList.dependencyNameWithRelease': string
  'versionDetails.dependencyList.table.columns.name': string
  'versionDetails.dependencyList.table.columns.version': string
  'versionDetails.deploymentsTable.columns.deploymentPipeline': string
  'versionDetails.deploymentsTable.columns.environment': string
  'versionDetails.deploymentsTable.columns.infra': string
  'versionDetails.deploymentsTable.columns.instanceCount': string
  'versionDetails.deploymentsTable.columns.services': string
  'versionDetails.deploymentsTable.columns.triggeredBy': string
  'versionDetails.deploymentsTable.columns.type': string
  'versionDetails.deploymentsTable.noDeploymentsTitle': string
  'versionDetails.noDependencies': string
  'versionDetails.overview.generalInformation.artifactType': string
  'versionDetails.overview.generalInformation.buildHost': string
  'versionDetails.overview.generalInformation.buildTime': string
  'versionDetails.overview.generalInformation.createdAndLastModifiedAt': string
  'versionDetails.overview.generalInformation.createdAt': string
  'versionDetails.overview.generalInformation.description': string
  'versionDetails.overview.generalInformation.digest': string
  'versionDetails.overview.generalInformation.documentation': string
  'versionDetails.overview.generalInformation.downloads': string
  'versionDetails.overview.generalInformation.hash': string
  'versionDetails.overview.generalInformation.homepage': string
  'versionDetails.overview.generalInformation.language': string
  'versionDetails.overview.generalInformation.license': string
  'versionDetails.overview.generalInformation.modifiedAt': string
  'versionDetails.overview.generalInformation.name': string
  'versionDetails.overview.generalInformation.packageType': string
  'versionDetails.overview.generalInformation.packager': string
  'versionDetails.overview.generalInformation.platform': string
  'versionDetails.overview.generalInformation.projectUrl': string
  'versionDetails.overview.generalInformation.pullCommand': string
  'versionDetails.overview.generalInformation.pullCommandByDigest': string
  'versionDetails.overview.generalInformation.ref': string
  'versionDetails.overview.generalInformation.repository': string
  'versionDetails.overview.generalInformation.repositoryPath': string
  'versionDetails.overview.generalInformation.size': string
  'versionDetails.overview.generalInformation.sourceRpm': string
  'versionDetails.overview.generalInformation.tags': string
  'versionDetails.overview.generalInformation.title': string
  'versionDetails.overview.generalInformation.uploadedBy': string
  'versionDetails.overview.generalInformation.url': string
  'versionDetails.overview.generalInformation.vcs': string
  'versionDetails.overview.generalInformation.vendor': string
  'versionDetails.overview.generalInformation.version': string
  'versionDetails.page': string
  'versionDetails.quarantineVersionModal.cancelButtonText': string
  'versionDetails.quarantineVersionModal.confirmButtonText': string
  'versionDetails.quarantineVersionModal.contentText': string
  'versionDetails.quarantineVersionModal.reasonField': string
  'versionDetails.quarantineVersionModal.title': string
  'versionDetails.quarantineVersionModal.versionQuarantined': string
  'versionDetails.removeFromQuarantineModal.cancelButtonText': string
  'versionDetails.removeFromQuarantineModal.confirmButtonText': string
  'versionDetails.removeFromQuarantineModal.contentText': string
  'versionDetails.removeFromQuarantineModal.title': string
  'versionDetails.removeFromQuarantineModal.versionRemovedFromQuarantine': string
  'versionDetails.restoreModal.contentText': string
  'versionDetails.restoreModal.inputLabel': string
  'versionDetails.restoreModal.inputPlaceholder': string
  'versionDetails.restoreModal.title': string
  'versionDetails.selectDigestPlaceholder': string
  'versionDetails.softDeleteModal.contentText': string
  'versionDetails.softDeleteModal.inputLabel': string
  'versionDetails.softDeleteModal.inputPlaceholder': string
  'versionDetails.softDeleteModal.title': string
  'versionDetails.tabs.artifactDetails': string
  'versionDetails.tabs.code': string
  'versionDetails.tabs.deployments': string
  'versionDetails.tabs.overview': string
  'versionDetails.tabs.securityTests': string
  'versionDetails.tabs.supplyChain': string
  'versionDetails.versionArchived': string
  'versionDetails.versionDeleted': string
  'versionDetails.versionRestored': string
  'versionList.actions.archiveVersion': string
  'versionList.actions.deleteVersion': string
  'versionList.actions.quarantine': string
  'versionList.actions.removeQuarantine': string
  'versionList.actions.restoreVersion': string
  'versionList.page': string
  'versionList.table.columns.activelyDeployed': string
  'versionList.table.columns.archivedAt': string
  'versionList.table.columns.deployments': string
  'versionList.table.columns.digests': string
  'versionList.table.columns.downloads': string
  'versionList.table.columns.fileCount': string
  'versionList.table.columns.publishedByAt': string
  'versionList.table.columns.pullCommand': string
  'versionList.table.columns.size': string
  'versionList.table.columns.tags': string
  'versionList.table.columns.version': string
  'versionList.table.noArchivedVersionsTitle': string
  'versionList.table.noVersionsTitle': string
  'violationsList.page': string
  'webhookDetails.tabs.configuration': string
  'webhookDetails.tabs.executions': string
  'webhookExecutionList.executionDetailsDrawer.at': string
  'webhookExecutionList.executionDetailsDrawer.duration': string
  'webhookExecutionList.executionDetailsDrawer.durationValue': string
  'webhookExecutionList.executionDetailsDrawer.error': string
  'webhookExecutionList.executionDetailsDrawer.payload': string
  'webhookExecutionList.executionDetailsDrawer.response': string
  'webhookExecutionList.executionDetailsDrawer.status': string
  'webhookExecutionList.executionDetailsDrawer.triggeredEvent': string
  'webhookExecutionList.retriggerExecution': string
  'webhookExecutionList.retriggerExecutionSuccess': string
  'webhookExecutionList.table.columns.event': string
  'webhookExecutionList.table.columns.id': string
  'webhookExecutionList.table.columns.lastTriggered': string
  'webhookExecutionList.table.columns.payload': string
  'webhookExecutionList.table.columns.response': string
  'webhookExecutionList.table.columns.status': string
  'webhookList.deleteModal.message': string
  'webhookList.deleteModal.title': string
  'webhookList.formFields.SSLVerification': string
  'webhookList.formFields.addNewKeyValuePair': string
  'webhookList.formFields.advanced': string
  'webhookList.formFields.allTrigger': string
  'webhookList.formFields.customTrigger': string
  'webhookList.formFields.description': string
  'webhookList.formFields.enableSSLVerification': string
  'webhookList.formFields.enabled': string
  'webhookList.formFields.extraHeader': string
  'webhookList.formFields.extraHeaderPlaceholder': string
  'webhookList.formFields.extraValue': string
  'webhookList.formFields.extraValuePlaceholder': string
  'webhookList.formFields.id': string
  'webhookList.formFields.name': string
  'webhookList.formFields.secret': string
  'webhookList.formFields.triggerLabel': string
  'webhookList.formFields.url': string
  'webhookList.newWebhook': string
  'webhookList.table.columns.name': string
  'webhookList.table.columns.trigger': string
  'webhookList.table.noWebhooksTitle': string
  'webhookList.triggers.artifactCreation': string
  'webhookList.triggers.artifactDeletion': string
  'webhookList.triggers.artifactModification': string
  'webhookList.webhookCreated': string
  'webhookList.webhookDeleted': string
  'webhookList.webhookUpdated': string
  'actions.copyCommand': string
  'actions.delete': string
  'actions.edit': string
  'actions.executions': string
  'actions.quarantine': string
  'actions.restore': string
  'actions.scan': string
  'actions.setupClient': string
  'actions.softDelete': string
  add: string
  addMetadata: string
  addProperty: string
  all: string
  apply: string
  archived: string
  available: string
  'badges.accountScope': string
  'badges.artifactRegistry': string
  'badges.orgScope': string
  'badges.projectScope': string
  'badges.quarantined': string
  'badges.upstreamProxy': string
  beta: string
  'breadcrumbs.artifacts': string
  'breadcrumbs.repositories': string
  'breadcrumbs.upstreamProxies': string
  cancel: string
  'cleanupPolicy.addBtn': string
  'cleanupPolicy.addPattern': string
  'cleanupPolicy.cleanUpByArtifactsOlderThan': string
  'cleanupPolicy.cleanUpByArtifactsOlderThanPlaceholder': string
  'cleanupPolicy.cleanUpByPackagePrefixes': string
  'cleanupPolicy.cleanUpByTagPrefixes': string
  'cleanupPolicy.cleanUpByVersionPrefixes': string
  'cleanupPolicy.infoMessage': string
  'cleanupPolicy.name': string
  'cleanupPolicy.placeholder': string
  clearFilters: string
  comingSoon: string
  copied: string
  copy: string
  createdAt: string
  customMetadata: string
  dateLabel: string
  delete: string
  deleted: string
  description: string
  descriptionPlaceholder: string
  details: string
  discard: string
  download: string
  encrypted: string
  enterPlaceholder: string
  failed: string
  failedToLoadData: string
  harLabel: string
  harnessAI: string
  id: string
  key: string
  'labels.addLabel': string
  'labels.addNewValue': string
  'labels.addNewValueDynamic': string
  'labels.findALabel': string
  'labels.findAValue': string
  'labels.findOrAddValue': string
  'labels.title': string
  lastUpdated: string
  loadMore: string
  loading: string
  metadata: string
  modifiedAt: string
  moduleName: string
  na: string
  new: string
  noDescription: string
  noMatchingFilterData: string
  noReadme: string
  noResultsFound: string
  nonProd: string
  nonProdCount: string
  optionalField: string
  'packageTypes.cargoPackage': string
  'packageTypes.condaPackage': string
  'packageTypes.dartPackage': string
  'packageTypes.dockerPackage': string
  'packageTypes.genericPackage': string
  'packageTypes.goPackage': string
  'packageTypes.helmPackage': string
  'packageTypes.huggingfacePackage': string
  'packageTypes.mavenPackage': string
  'packageTypes.npmPackage': string
  'packageTypes.nugetPackage': string
  'packageTypes.package': string
  'packageTypes.pythonPackage': string
  'packageTypes.rpmPackage': string
  plaintext: string
  plusNewName: string
  prod: string
  prodCount: string
  properties: string
  'publicAccess.oopsPageNotPublic': string
  'publicAccess.tryOtherOptions': string
  'repositoryTypes.alpine': string
  'repositoryTypes.cargo': string
  'repositoryTypes.composer': string
  'repositoryTypes.conda': string
  'repositoryTypes.dart': string
  'repositoryTypes.debian': string
  'repositoryTypes.docker': string
  'repositoryTypes.generic': string
  'repositoryTypes.go': string
  'repositoryTypes.gradle': string
  'repositoryTypes.helm': string
  'repositoryTypes.huggingface': string
  'repositoryTypes.maven': string
  'repositoryTypes.npm': string
  'repositoryTypes.nuget': string
  'repositoryTypes.pypi': string
  'repositoryTypes.rpm': string
  restore: string
  retriableError: string
  save: string
  search: string
  'sideNav.artifacts': string
  'sideNav.repositories': string
  'sideNav.upstreamProxies': string
  soon: string
  'status.archived': string
  'status.available': string
  stepNotFound: string
  success: string
  tabNotFound: string
  'tags.latest': string
  'tags.latestVersion': string
  tagsLabel: string
  timeLabel: string
  unknown: string
  'validationMessages.accessKeyRequired': string
  'validationMessages.cleanupPolicy.expireDaysRequired': string
  'validationMessages.cleanupPolicy.nameRequired': string
  'validationMessages.cleanupPolicy.positiveExpireDays': string
  'validationMessages.entityRequired': string
  'validationMessages.equals': string
  'validationMessages.genericURLPattern': string
  'validationMessages.headerAlreadyExists': string
  'validationMessages.identifierRequired': string
  'validationMessages.nameRequired': string
  'validationMessages.noNewLine': string
  'validationMessages.passwordRequired': string
  'validationMessages.repokeyRegExMessage': string
  'validationMessages.required': string
  'validationMessages.secretKeyRequired': string
  'validationMessages.stringMax': string
  'validationMessages.uniqueValues': string
  'validationMessages.urlPattern': string
  'validationMessages.urlRequired': string
  'validationMessages.userNameRequired': string
  value: string
  view: string
  'vulnerabilityStatus.critical': string
  'vulnerabilityStatus.high': string
  'vulnerabilityStatus.low': string
  'vulnerabilityStatus.medium': string
}
