/* eslint-disable */
// This is an auto-generated file
export declare const button: string
export declare const buttonContainer: string
export declare const buttonText: string
export declare const checkbox: string
export declare const content: string
export declare const deleteBtn: string
export declare const deleteContainer: string
export declare const detailsLabel: string
export declare const dividerContainer: string
export declare const generalContainer: string
export declare const harnessUpgradeWatermark: string
export declare const harnessWatermark: string
export declare const icon: string
export declare const importContainer: string
export declare const label: string
export declare const mainContainer: string
export declare const mainCtn: string
export declare const progressBar: string
export declare const repoInfo: string
export declare const roleBadge: string
export declare const saveBtn: string
export declare const textContainer: string
export declare const upgradeButton: string
export declare const upgradeContainer: string
export declare const upgradeHeader: string
export declare const verticalContainer: string
export declare const yellowContainer: string
