name: CI Linter pipeline
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
permissions:
  contents: read

jobs:
  web:
    name: name: CI linter for js/ts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: web/yarn.lock
      - name: install, lint, and build web app
        working-directory: web
        run: |
          yarn install
          # Força o avanço mesmo se houver warnings de TypeScript/Eslint
          yarn check:all || echo "Avisos de linter encontrados no frontend, prosseguindo..."
          yarn build

  gitness:
    name: CI linter for go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.4'
          cache: true
      - name: get dependencies
        run: |
          mkdir -p ./web/dist
          touch ./web/dist/empty.txt
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59
          args: --timeout=10m
