name: CI Linter pipeline
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
permissions:
  contents: read

jobs:
  web:
    name: CI linter for js/ts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "yarn" 
          cache-dependency-path: web/yarn.lock
      - name: install, lint, and build web app
        working-directory: web
        continue-on-error: true
        run: |
          yarn install
          yarn check:all
          yarn build

  gitness:
    name: CI linter for go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.0' # Alinhado exatamente com a versão do binário do golangci-lint
          cache: true
          cache-dependency-path: go.sum
      - name: get dependencies
        run: |
          mkdir -p ./web/dist
          touch ./web/dist/empty.txt
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        continue-on-error: true
        env:
          GOGC: "10"
          GOMEMLIMIT: "4GiB"
        with:
          version: v1.64 # Utiliza a v1.64.8 estável instalada pelo runner
          args: --timeout=30m --concurrency=2 ./...
