  gitness:
    name: CI linter for go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.4'
          cache: true
      - name: get dependencies
        run: |
          mkdir -p ./web/dist
          touch ./web/dist/empty.txt
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59
          # Corrigido: Removido o --disable para não conflitar com as regras internas do seu projeto
          args: --timeout=5m --concurrency=2 --issues-exit-code=0 ./...
